/**
 * 中节能低碳园区微电网数字化平台 - 场景数据底座
 * 严格遵从一期边界：
 * - 单试点站点：低碳园区示范站
 * - 统一实体 ID 映射
 * - 场景 A：正常运营
 * - 场景 B：储能 EMS 异常闭环
 */

import {
  UserRole,
  Site,
  IntegrationAdapter,
  Device,
  Point,
  DataQualityIssue,
  TariffScheme,
  TariffVersion,
  RevenueSnapshot,
  RecalculationBatch,
  Alarm,
  AgentEvent,
  PatrolPlan,
  PatrolTask,
  PatrolRecord,
  WorkOrder,
  AuditLog,
  ReportItem,
  User,
  Role,
} from '../types/domain';

// 当前试点站点：低碳园区示范站 (一期)
export const MOCK_SITE: Site = {
  id: 'SITE-001',
  name: '低碳园区示范站 (一期)',
  code: 'CECEP-001',
  location: '福建省高新技术产业开发区低碳创新示范园 A1 区',
  pvCapacity: '1.2 MWp (分布式屋顶光伏)',
  pvCapacityKwp: 1200,
  storageCapacity: '500 kW / 1000 kWh (磷酸铁锂储能系统)',
  storageCapacityKwh: 1000,
  chargerCount: 12,
  status: 'ONLINE',
  gridVoltage: '10 kV (三相交流并网)',
  transformerCapacity: '2000 kVA',
  commissioningDate: '2025-08-18',
};

// 多站点管理配置底座
export const MOCK_SITES: Site[] = [
  MOCK_SITE,
  {
    id: 'SITE-002',
    name: '滨海智造绿色产业园 (二期)',
    code: 'CECEP-002',
    location: '江苏省沿海智造工业聚集区能源管理中心 B3 区',
    pvCapacity: '2.5 MWp (BAPV建筑屋顶光伏)',
    pvCapacityKwp: 2500,
    storageCapacity: '1000 kW / 2000 kWh (液冷集装箱储能)',
    storageCapacityKwh: 2000,
    chargerCount: 20,
    status: 'ONLINE',
    gridVoltage: '10 kV (双回路专线并网)',
    transformerCapacity: '3150 kVA',
    commissioningDate: '2025-11-20',
  },
  {
    id: 'SITE-003',
    name: '高新综合智慧能源港 (三期)',
    code: 'CECEP-003',
    location: '广东省大湾区先进制造与超算互联港 C2 枢纽',
    pvCapacity: '3.0 MWp (柔性支架与光伏幕墙)',
    pvCapacityKwp: 3000,
    storageCapacity: '2000 kW / 4000 kWh (半固态高安全储能)',
    storageCapacityKwh: 4000,
    chargerCount: 32,
    status: 'ONLINE',
    gridVoltage: '35 kV (高压用户并网站)',
    transformerCapacity: '5000 kVA',
    commissioningDate: '2026-03-15',
  },
];

// 预设用户角色
export const MOCK_USERS: User[] = [
  {
    id: 'USR-ADMIN-01',
    username: 'admin_cecep',
    name: '张宇轩',
    role: 'ADMIN',
    roleTitle: '系统管理员',
    status: 'ACTIVE',
    department: '中节能数字化中心 / 平台技术部',
    phone: '138-0010-8801',
    email: 'yuxuan.zhang@cecep.cn',
    wechat: 'wx_cecep_zyx',
    lastLoginTime: '2026-09-05 06:12:30',
    createdAt: '2025-08-01',
  },
  {
    id: 'USR-OPER-02',
    username: 'operator_chen',
    name: '陈若涵',
    role: 'OPERATOR',
    roleTitle: '微电网运营主管',
    status: 'ACTIVE',
    department: '园区运营部 / 能效管理中心',
    phone: '139-0596-6602',
    email: 'ruohan.chen@cecep.cn',
    wechat: 'wx_cecep_crh',
    lastLoginTime: '2026-09-05 05:50:18',
    createdAt: '2025-08-01',
  },
  {
    id: 'USR-INSP-03',
    username: 'inspector_lin',
    name: '林志强',
    role: 'INSPECTOR',
    roleTitle: '现场特种运维巡检员',
    status: 'ACTIVE',
    department: '中节能物业 / 现场工程组',
    phone: '137-0596-7703',
    email: 'zhiqiang.lin@cecep.cn',
    wechat: 'wx_cecep_lzq',
    lastLoginTime: '2026-09-05 04:35:40',
    createdAt: '2025-08-10',
  },
  {
    id: 'USR-INSP-04',
    username: 'inspector_wang',
    name: '王浩然',
    role: 'INSPECTOR',
    roleTitle: '现场电气备班巡检员',
    status: 'ACTIVE',
    department: '中节能物业 / 现场工程组',
    phone: '136-0596-3304',
    email: 'haoran.wang@cecep.cn',
    wechat: 'wx_cecep_whr',
    lastLoginTime: '2026-09-04 17:30:12',
    createdAt: '2025-09-01',
  },
];

export interface PermissionDefinition {
  key: string;
  name: string;
  category: 'ACTION' | 'MENU';
  riskLevel: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  description: string;
  mutuallyExclusiveWith?: string; // 互斥权限代码
  conflictReason?: string;
}

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  // 关键操作与按钮级权限
  {
    key: 'tariff_submit',
    name: '电价草稿起草与提交',
    category: 'ACTION',
    riskLevel: 'HIGH',
    description: '起草分时电价方案、峰谷平时段与费率变更，并提交进入审批流。',
    mutuallyExclusiveWith: 'tariff_approve',
    conflictReason: '违反内部控制两票制三权分立原则：同一角色严禁同时拥有【电价草稿提交】与【电价二次授权审批】权限！',
  },
  {
    key: 'tariff_approve',
    name: '电价二次授权审批生效',
    category: 'ACTION',
    riskLevel: 'CRITICAL',
    description: '对电价方案版本进行两票制二次审批授权并正式生效，直接影响结算电费核算。',
    mutuallyExclusiveWith: 'tariff_submit',
    conflictReason: '违反内部控制两票制三权分立原则：同一角色严禁同时拥有【电价草稿提交】与【电价二次授权审批】权限！',
  },
  {
    key: 'revenue_recalc',
    name: '收益重算与偏差回溯触发',
    category: 'ACTION',
    riskLevel: 'HIGH',
    description: '在计量数据补采完成后，手工触发日终收益 T+1 全量重算并生成覆盖快照。',
  },
  {
    key: 'system_config',
    name: '系统安全与底层适配器配置',
    category: 'ACTION',
    riskLevel: 'CRITICAL',
    description: '修改工业规约通信参数、IP 地址、重试阈值及用户权限矩阵分配。',
  },
  {
    key: 'data_backfill_collect',
    name: '点位断点补采与数据治理',
    category: 'ACTION',
    riskLevel: 'MEDIUM',
    description: '对通信中断丢失的采样点发起主动重采、插值拟合与异常标记。',
  },
  {
    key: 'alarm_handle_suppress',
    name: '告警确认处置与静默抑制',
    category: 'ACTION',
    riskLevel: 'MEDIUM',
    description: '在 SLA 时限内人工确认为通信闪断或误报，或执行告警转工单派发。',
  },
  {
    key: 'workorder_review',
    name: '现场整改工单复核与归档',
    category: 'ACTION',
    riskLevel: 'MEDIUM',
    description: '审查现场特种作业整改照片与证据，执行工单通过关闭或打回重做。',
  },
  {
    key: 'report_export',
    name: '综合报表导出与流水下载',
    category: 'ACTION',
    riskLevel: 'LOW',
    description: '导出运营日报、月度核算结算单、巡检台账及不可篡改审计流水 CSV。',
  },
  // 菜单与视图访问权限
  {
    key: 'menu_data_integrations',
    name: '菜单: 接入适配器 (/data/integrations)',
    category: 'MENU',
    riskLevel: 'HIGH',
    description: '进入工业物联适配器接入配置页面。',
  },
  {
    key: 'menu_data_points',
    name: '菜单: 点位映射与质量 (/data/points)',
    category: 'MENU',
    riskLevel: 'MEDIUM',
    description: '进入点位资产映射表与数据质量规则视图。',
  },
  {
    key: 'menu_tariffs',
    name: '菜单: 分时电价方案 (/tariffs)',
    category: 'MENU',
    riskLevel: 'MEDIUM',
    description: '进入分时电价方案与生效版本管理页面。',
  },
  {
    key: 'menu_screen',
    name: '菜单: 运行大屏与看板 (/screen, /dashboard)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入全站微电网综合拓扑监控大屏与管理驾驶舱。',
  },
  {
    key: 'menu_monitor_flow',
    name: '菜单: 能量平衡流向 (/monitor/flow)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入光储充用母线能量平衡流向与实时功率监测。',
  },
  {
    key: 'menu_monitor_devices',
    name: '菜单: 设备台账工况 (/monitor/devices)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入逆变器、变流器、箱变、充电桩设备台账及工况。',
  },
  {
    key: 'menu_alarms',
    name: '菜单: 告警中心与 SLA (/alarms)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入全站告警中心与 SLA 响应处置。',
  },
  {
    key: 'menu_agent_hub',
    name: '菜单: Agent Hub 策略辅助 (/agent-hub)',
    category: 'MENU',
    riskLevel: 'MEDIUM',
    description: '进入微电网 AI 策略研判与规则降级控制中心。',
  },
  {
    key: 'menu_operations_plans',
    name: '菜单: 巡检计划编制 (/operations/plans)',
    category: 'MENU',
    riskLevel: 'MEDIUM',
    description: '进入巡检周期计划编制与排程维护。',
  },
  {
    key: 'menu_operations_tasks',
    name: '菜单: 巡检任务调度 (/operations/tasks)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入巡检任务派发、进度跟踪与任务看板。',
  },
  {
    key: 'menu_operations_work_orders',
    name: '菜单: 现场整改工单 (/operations/work-orders)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入现场缺陷闭环整改工单处理流。',
  },
  {
    key: 'menu_operations_records',
    name: '菜单: 巡检历史归档 (/operations/records)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入巡检历史电子存证与防篡改档案。',
  },
  {
    key: 'menu_reports',
    name: '菜单: 报表中心 (/reports)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入运营日报、月报、结算单与报表生成。',
  },
  {
    key: 'menu_admin_users',
    name: '菜单: 用户管理 (/admin/users)',
    category: 'MENU',
    riskLevel: 'HIGH',
    description: '进入人员账号管理、状态启停与密码重置。',
  },
  {
    key: 'menu_admin_roles',
    name: '菜单: 角色权限矩阵 (/admin/roles)',
    category: 'MENU',
    riskLevel: 'CRITICAL',
    description: '进入三权分立权限矩阵与安全互斥策略。',
  },
  {
    key: 'menu_admin_audit',
    name: '菜单: 系统操作日志 (/admin/audit)',
    category: 'MENU',
    riskLevel: 'LOW',
    description: '进入不可篡改业务操作审计流水查询。',
  },
  {
    key: 'menu_admin_health',
    name: '菜单: 平台健康诊断 (/admin/health)',
    category: 'MENU',
    riskLevel: 'MEDIUM',
    description: '进入平台微服务、适配器与数据链路健康自检。',
  },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  ADMIN: [
    // 菜单全部开放
    'menu_data_integrations',
    'menu_data_points',
    'menu_tariffs',
    'menu_screen',
    'menu_monitor_flow',
    'menu_monitor_devices',
    'menu_alarms',
    'menu_agent_hub',
    'menu_operations_plans',
    'menu_operations_tasks',
    'menu_operations_work_orders',
    'menu_operations_records',
    'menu_reports',
    'menu_admin_users',
    'menu_admin_roles',
    'menu_admin_audit',
    'menu_admin_health',
    // 管理员按钮权限：拥有二次审批、配置、重算、补采、复核、导出，严格互斥没有电价草稿提交权
    'tariff_approve',
    'data_backfill_collect',
    'alarm_handle_suppress',
    'workorder_review',
    'revenue_recalc',
    'report_export',
    'system_config',
  ],
  OPERATOR: [
    // 业务菜单开放，系统级配置禁用
    'menu_data_points',
    'menu_tariffs',
    'menu_screen',
    'menu_monitor_flow',
    'menu_monitor_devices',
    'menu_alarms',
    'menu_agent_hub',
    'menu_operations_plans',
    'menu_operations_tasks',
    'menu_operations_work_orders',
    'menu_operations_records',
    'menu_reports',
    'menu_admin_audit',
    'menu_admin_health',
    // 运营人员按钮权限：拥有电价起草、告警处置、工单复核、收益重算、报表导出、补采，严格互斥没有电价审批权与系统配置权
    'tariff_submit',
    'data_backfill_collect',
    'alarm_handle_suppress',
    'workorder_review',
    'revenue_recalc',
    'report_export',
  ],
  INSPECTOR: [
    // 巡检移动端与现场现场视图
    'menu_alarms',
    'menu_operations_tasks',
    'menu_operations_work_orders',
    'menu_operations_records',
    // 巡检员按钮权限：现场告警确认
    'alarm_handle_suppress',
  ],
};

export const MOCK_ROLES: Role[] = [
  {
    id: 'ADMIN',
    name: '系统管理员',
    description: '负责接入适配器、映射配置、数据质量校验规则、用户权限配置与电价生效二次授权。',
    defaultLandingRoute: '/data/integrations',
    permissions: ['DATA_INGEST_MANAGE', 'MAPPING_EDIT', 'QUALITY_RULE_CONFIG', 'TARIFF_AUTHORIZE', 'USER_ROLE_MANAGE', 'AUDIT_VIEW'],
  },
  {
    id: 'OPERATOR',
    name: '运营人员',
    description: '负责首页看板、电网平衡监控、电价版本起草、告警复核、工单派发、收益核算重算及 Agent 策略审核。',
    defaultLandingRoute: '/agent-hub',
    permissions: ['DASHBOARD_VIEW', 'AGENT_HUB_MANAGE', 'TARIFF_DRAFT', 'ALARM_DISPATCH', 'REVENUE_RECALC_INITIATE', 'WORKORDER_AUDIT'],
  },
  {
    id: 'INSPECTOR',
    name: '巡检员',
    description: '负责现场巡检任务接收、移动端逐项点检、离线数据记录、异常上报与整改工单现场复查反馈。',
    defaultLandingRoute: '/mobile/tasks',
    permissions: ['PATROL_TASK_EXECUTE', 'MOBILE_RECORD_SUBMIT', 'WORKORDER_FEEDBACK', 'OFFLINE_CACHE_MANAGE'],
  },
];

// 电价方案与版本
export const MOCK_TARIFF_VERSIONS: TariffVersion[] = [
  {
    id: 'VER-TARIFF-V1',
    schemeId: 'SCHEME-TOU',
    versionNumber: 'V1.0',
    effectiveDateStart: '2026-01-01',
    effectiveDateEnd: '2026-08-31',
    effectiveDate: '2026-01-01',
    slots: [
      { label: '尖峰', period: '19:00 - 21:00', price: 1.425 },
      { label: '高峰', period: '08:30 - 11:30, 14:30 - 19:00', price: 1.128 },
      { label: '平段', period: '06:30 - 08:30, 11:30 - 14:30, 21:00 - 23:00', price: 0.685 },
      { label: '低谷', period: '23:00 - 次日06:30', price: 0.326 },
      { label: '深谷', period: '特定窗口备选 (12:00 - 14:00)', price: 0.218 },
    ],
    timeIntervals: [
      { id: 't1-1', start: '00:00', end: '06:30', label: '低谷', price: 0.326 },
      { id: 't1-2', start: '06:30', end: '08:30', label: '平段', price: 0.685 },
      { id: 't1-3', start: '08:30', end: '11:30', label: '高峰', price: 1.128 },
      { id: 't1-4', start: '11:30', end: '14:30', label: '平段', price: 0.685 },
      { id: 't1-5', start: '14:30', end: '19:00', label: '高峰', price: 1.128 },
      { id: 't1-6', start: '19:00', end: '21:00', label: '尖峰', price: 1.425 },
      { id: 't1-7', start: '21:00', end: '23:00', label: '平段', price: 0.685 },
      { id: 't1-8', start: '23:00', end: '24:00', label: '低谷', price: 0.326 },
    ],
    serviceFeeOrBaseFee: '充电桩服务费: 0.40元/kWh | 容量电费: 32.00元/kVA/月 (装见容量2000kVA)',
    status: 'EFFECTIVE',
    creator: '陈若涵 (运营人员)',
    approver: '张宇轩 (系统管理员二次授权)',
    approvalTime: '2025-12-28 16:30:00',
    authorizedAt: '2025-12-28 16:30:00',
    notes: '市发展和改革委 2026 年度大工业工商业分时电价核定标准。',
    pvConfig: {
      mode: 'FIXED',
      fixedPrice: 0.3916,
      description: '全额及余电上网按福建省标杆燃煤脱硫基准价 0.3916 元/kWh 执行固定结算。',
    },
    chargingConfig: {
      serviceFee: 0.40,
      energyPriceTou: {
        sharp: 1.425,
        peak: 1.128,
        flat: 0.685,
        valley: 0.326,
        deepValley: 0.218,
      },
    },
    basicFeeConfig: {
      type: 'CAPACITY',
      capacityUnitPrice: 32.0,
      transformerCapacityKva: 2000,
      description: '选用【容量电费】：变压器装见容量 2000 kVA × 32.00 元/kVA/月 = 64,000 元/月；需量电费停用。',
    },
    approvalRecords: [
      {
        id: 'APR-V1-01',
        versionNumber: 'V1.0',
        action: 'CREATE_DRAFT',
        actionName: '编制电价草稿',
        operatorName: '陈若涵',
        role: 'OPERATOR',
        timestamp: '2025-12-26 10:15:00',
        notes: '根据省发改委最新工商业目录分时标准录入',
      },
      {
        id: 'APR-V1-02',
        versionNumber: 'V1.0',
        action: 'SUBMIT',
        actionName: '提交二次授权审批',
        operatorName: '陈若涵',
        role: 'OPERATOR',
        timestamp: '2025-12-26 14:20:00',
        notes: '完成 24 小时无重叠无留空校验，提交审批',
      },
      {
        id: 'APR-V1-03',
        versionNumber: 'V1.0',
        action: 'AUTHORIZE',
        actionName: '系统管理员二次授权生效',
        operatorName: '张宇轩',
        role: 'ADMIN',
        timestamp: '2025-12-28 16:30:00',
        notes: '复核发改委批文一致，授权生效并作为综合核算唯一基准',
      },
    ],
  },
  {
    id: 'VER-TARIFF-V2',
    schemeId: 'SCHEME-TOU',
    versionNumber: 'V2.0',
    effectiveDateStart: '2026-09-01',
    effectiveDateEnd: '2026-12-31',
    slots: [
      { label: '尖峰', period: '19:00 - 21:00', price: 1.488 },
      { label: '高峰', period: '08:30 - 11:30, 14:30 - 19:00', price: 1.165 },
      { label: '平段', period: '06:30 - 08:30, 11:30 - 12:00, 14:00 - 14:30, 21:00 - 23:00', price: 0.692 },
      { label: '低谷', period: '23:00 - 次日06:30', price: 0.315 },
      { label: '深谷', period: '午间光伏富余消纳窗口 12:00 - 14:00', price: 0.205 },
    ],
    timeIntervals: [
      { id: 't2-1', start: '00:00', end: '06:30', label: '低谷', price: 0.315 },
      { id: 't2-2', start: '06:30', end: '08:30', label: '平段', price: 0.692 },
      { id: 't2-3', start: '08:30', end: '11:30', label: '高峰', price: 1.165 },
      { id: 't2-4', start: '11:30', end: '12:00', label: '平段', price: 0.692 },
      { id: 't2-5', start: '12:00', end: '14:00', label: '深谷', price: 0.205 },
      { id: 't2-6', start: '14:00', end: '14:30', label: '平段', price: 0.692 },
      { id: 't2-7', start: '14:30', end: '19:00', label: '高峰', price: 1.165 },
      { id: 't2-8', start: '19:00', end: '21:00', label: '尖峰', price: 1.488 },
      { id: 't2-9', start: '21:00', end: '23:00', label: '平段', price: 0.692 },
      { id: 't2-10', start: '23:00', end: '24:00', label: '低谷', price: 0.315 },
    ],
    serviceFeeOrBaseFee: '充电桩服务费: 0.42元/kWh | 需量电费: 40.00元/kW/月 (核定需量1200kW)',
    status: 'PENDING_APPROVAL',
    creator: '陈若涵 (运营人员)',
    submitTime: '2026-08-28 09:30:00',
    notes: '迎峰度夏及秋季分时时段细化调整方案，午间增设深谷激励光伏就地消纳，基本电费优化为最大需量计费。等待管理员二次授权审批。',
    pvConfig: {
      mode: 'TIERED',
      tieredConfig: {
        thresholdKwh: 500000,
        tier1Price: 0.4150,
        tier2Price: 0.3800,
      },
      description: '采用【阶梯电价】：月度累计上网电量 ≤500MWh 结算价 0.4150 元/kWh；超额部分 0.3800 元/kWh。',
    },
    chargingConfig: {
      serviceFee: 0.42,
      energyPriceTou: {
        sharp: 1.488,
        peak: 1.165,
        flat: 0.692,
        valley: 0.315,
        deepValley: 0.205,
      },
    },
    basicFeeConfig: {
      type: 'DEMAND',
      demandUnitPrice: 40.0,
      declaredDemandKw: 1200,
      description: '选用【需量电费】：核定申报需量 1200 kW × 40.00 元/kW/月 = 48,000 元/月；容量电费停用，预期月度节省基本电费 16,000 元。',
    },
    approvalRecords: [
      {
        id: 'APR-V2-01',
        versionNumber: 'V2.0',
        action: 'CREATE_DRAFT',
        actionName: '编制新版本草稿',
        operatorName: '陈若涵',
        role: 'OPERATOR',
        timestamp: '2026-08-27 15:40:00',
        notes: '根据秋季负荷及需量优化分析拟定 V2.0 草稿方案',
      },
      {
        id: 'APR-V2-02',
        versionNumber: 'V2.0',
        action: 'SUBMIT',
        actionName: '提交二次授权审批',
        operatorName: '陈若涵',
        role: 'OPERATOR',
        timestamp: '2026-08-28 09:30:00',
        notes: '校验 24 小时时段连续覆盖无重叠，时段价格校验通过，提交系统管理员审批',
      },
    ],
  },
];

export const MOCK_TARIFF_SCHEME: TariffScheme = {
  id: 'SCHEME-SITE-001',
  siteId: 'SITE-001',
  name: '示范站大工业分时与微网综合计费方案',
  type: 'TOU_GRID_PURCHASE',
  status: 'ACTIVE',
  currentVersion: 'V1.0',
  versions: MOCK_TARIFF_VERSIONS,
};

// 站点 SITE-002 专属电价方案 (江苏沿海 10kV 两部制分时电价)
export const MOCK_TARIFF_SCHEME_SITE_002: TariffScheme = {
  id: 'SCHEME-SITE-002',
  siteId: 'SITE-002',
  name: '滨海绿色产业园大工业分时与需量计费方案',
  type: 'TOU_GRID_PURCHASE',
  status: 'ACTIVE',
  currentVersion: 'V1.0',
  versions: [
    {
      id: 'VER-SITE2-V1',
      schemeId: 'SCHEME-SITE-002',
      versionNumber: 'V1.0',
      effectiveDateStart: '2025-11-20',
      effectiveDateEnd: '2026-12-31',
      effectiveDate: '2025-11-20',
      authorizedAt: '2025-11-18 10:00:00',
      slots: [
        { label: '低谷', period: '00:00 - 08:00', price: 0.320 },
        { label: '平段', period: '08:00 - 10:00', price: 0.680 },
        { label: '高峰', period: '10:00 - 11:30', price: 1.185 },
        { label: '平段', period: '11:30 - 14:00', price: 0.680 },
        { label: '高峰', period: '14:00 - 17:00', price: 1.185 },
        { label: '平段', period: '17:00 - 19:00', price: 0.680 },
        { label: '尖峰', period: '19:00 - 21:00', price: 1.542 },
        { label: '平段', period: '21:00 - 23:00', price: 0.680 },
        { label: '低谷', period: '23:00 - 24:00', price: 0.320 },
      ],
      timeIntervals: [
        { id: 's2-1', start: '00:00', end: '08:00', label: '低谷', price: 0.320 },
        { id: 's2-2', start: '08:00', end: '10:00', label: '平段', price: 0.680 },
        { id: 's2-3', start: '10:00', end: '11:30', label: '高峰', price: 1.185 },
        { id: 's2-4', start: '11:30', end: '14:00', label: '平段', price: 0.680 },
        { id: 's2-5', start: '14:00', end: '17:00', label: '高峰', price: 1.185 },
        { id: 's2-6', start: '17:00', end: '19:00', label: '平段', price: 0.680 },
        { id: 's2-7', start: '19:00', end: '21:00', label: '尖峰', price: 1.542 },
        { id: 's2-8', start: '21:00', end: '23:00', label: '平段', price: 0.680 },
        { id: 's2-9', start: '23:00', end: '24:00', label: '低谷', price: 0.320 },
      ],
      serviceFeeOrBaseFee: '充电桩服务费: 0.45元/kWh | 最大需量计费: 40.00元/kW/月',
      status: 'EFFECTIVE',
      creator: '陈若涵',
      approver: '张宇轩',
      approvalTime: '2025-11-18 10:00:00',
      notes: '滨海智造二期标准大工业分时方案，核定需量 2000kW。',
      pvConfig: {
        mode: 'MARKET',
        marketConfig: {
          basePrice: 0.3910,
          floatingSpread: 0.0250,
        },
        description: '光伏上网采用电力现货市场化浮动月度结算。',
      },
      chargingConfig: {
        serviceFee: 0.45,
        energyPriceTou: {
          sharp: 1.542,
          peak: 1.185,
          flat: 0.680,
          valley: 0.320,
          deepValley: 0.210,
        },
      },
      basicFeeConfig: {
        type: 'DEMAND',
        demandUnitPrice: 40.0,
        declaredDemandKw: 2000,
        description: '选用【需量电费】：核定申报需量 2000 kW × 40.00 元/kW/月 = 80,000 元/月。',
      },
      approvalRecords: [
        {
          id: 'APR-S2-V1-01',
          versionNumber: 'V1.0',
          action: 'AUTHORIZE',
          actionName: '系统管理员二次授权生效',
          operatorName: '张宇轩',
          role: 'ADMIN',
          timestamp: '2025-11-18 10:00:00',
          notes: '二期投运基准方案授权批准生效',
        },
      ],
    },
  ],
};

// 站点 SITE-003 专属电价方案 (广东自贸区 35kV 大工业及现货分时方案)
export const MOCK_TARIFF_SCHEME_SITE_003: TariffScheme = {
  id: 'SCHEME-SITE-003',
  siteId: 'SITE-003',
  name: '大湾区综合智慧能源港 35kV 现货分时计费方案',
  type: 'TOU_GRID_PURCHASE',
  status: 'ACTIVE',
  currentVersion: 'V1.0',
  versions: [
    {
      id: 'VER-SITE3-V1',
      schemeId: 'SCHEME-SITE-003',
      versionNumber: 'V1.0',
      effectiveDateStart: '2026-03-15',
      effectiveDateEnd: '2027-03-14',
      effectiveDate: '2026-03-15',
      authorizedAt: '2026-03-12 14:30:00',
      slots: [
        { label: '低谷', period: '00:00 - 08:00', price: 0.290 },
        { label: '平段', period: '08:00 - 10:00', price: 0.650 },
        { label: '高峰', period: '10:00 - 12:00', price: 1.120 },
        { label: '深谷', period: '12:00 - 14:00', price: 0.180 },
        { label: '高峰', period: '14:00 - 19:00', price: 1.120 },
        { label: '尖峰', period: '19:00 - 21:00', price: 1.420 },
        { label: '平段', period: '21:00 - 23:00', price: 0.650 },
        { label: '低谷', period: '23:00 - 24:00', price: 0.290 },
      ],
      timeIntervals: [
        { id: 's3-1', start: '00:00', end: '08:00', label: '低谷', price: 0.290 },
        { id: 's3-2', start: '08:00', end: '10:00', label: '平段', price: 0.650 },
        { id: 's3-3', start: '10:00', end: '12:00', label: '高峰', price: 1.120 },
        { id: 's3-4', start: '12:00', end: '14:00', label: '深谷', price: 0.180 },
        { id: 's3-5', start: '14:00', end: '19:00', label: '高峰', price: 1.120 },
        { id: 's3-6', start: '19:00', end: '21:00', label: '尖峰', price: 1.420 },
        { id: 's3-7', start: '21:00', end: '23:00', label: '平段', price: 0.650 },
        { id: 's3-8', start: '23:00', end: '24:00', label: '低谷', price: 0.290 },
      ],
      serviceFeeOrBaseFee: '充电桩服务费: 0.38元/kWh | 容量电费: 35.00元/kVA/月 (主变 5000kVA)',
      status: 'EFFECTIVE',
      creator: '陈若涵',
      approver: '张宇轩',
      approvalTime: '2026-03-12 14:30:00',
      notes: '大湾区能源港 35kV 现货分时交易方案，中午 12:00-14:00 设深谷电价以消纳超发光伏。',
      pvConfig: {
        mode: 'FIXED',
        fixedPrice: 0.4530,
        description: '光伏上网采用大湾区绿电标杆固定上网电价 0.4530 元/kWh。',
      },
      chargingConfig: {
        serviceFee: 0.38,
        energyPriceTou: {
          sharp: 1.420,
          peak: 1.120,
          flat: 0.650,
          valley: 0.290,
          deepValley: 0.180,
        },
      },
      basicFeeConfig: {
        type: 'CAPACITY',
        capacityUnitPrice: 35.0,
        transformerCapacityKva: 5000,
        description: '选用【容量电费】：变压器容量 5000 kVA × 35.00 元/kVA/月 = 175,000 元/月。',
      },
      approvalRecords: [
        {
          id: 'APR-S3-V1-01',
          versionNumber: 'V1.0',
          action: 'AUTHORIZE',
          actionName: '系统管理员二次授权生效',
          operatorName: '张宇轩',
          role: 'ADMIN',
          timestamp: '2026-03-12 14:30:00',
          notes: '三期大容量自贸区试点电价核准生效',
        },
      ],
    },
  ],
};

// 多站点专属电价方案集合
export const MOCK_TARIFF_SCHEMES: TariffScheme[] = [
  MOCK_TARIFF_SCHEME,
  MOCK_TARIFF_SCHEME_SITE_002,
  MOCK_TARIFF_SCHEME_SITE_003,
];

// 场景 A 初始状态
export function getScenarioAState() {
  const adapters: IntegrationAdapter[] = [
    {
      id: 'ADAPTER-PV-01',
      type: 'PV_INVERTER',
      platformName: '阳光电源 Sungrow iSolarCloud 接口',
      protocol: 'Modbus-TCP / API',
      authType: 'API_KEY',
      syncMode: 'INTERVAL_POLL_1M',
      status: 'ONLINE',
      lastSyncTime: '刚刚 (2026-09-05 06:12:30)',
      consecutiveFailures: 0,
    },
    {
      id: 'ADAPTER-STORAGE-02',
      type: 'STORAGE_EMS',
      platformName: '时代星云 CATL-Nebula EMS 本地通信网关',
      protocol: 'IEC 61850 / REST',
      authType: 'CERTIFICATE',
      syncMode: 'REALTIME_PUSH',
      status: 'ONLINE',
      lastSyncTime: '刚刚 (2026-09-05 06:12:45)',
      consecutiveFailures: 0,
    },
    {
      id: 'ADAPTER-CHARGER-03',
      type: 'CHARGING_PLATFORM',
      platformName: '特来电 TELD 智能桩群云端中继',
      protocol: 'MQTT / JSON',
      authType: 'TOKEN_BEARER',
      syncMode: 'INTERVAL_POLL_1M',
      status: 'ONLINE',
      lastSyncTime: '1分钟前 (2026-09-05 06:11:58)',
      consecutiveFailures: 0,
    },
    {
      id: 'ADAPTER-GRID-04',
      type: 'GRID_METER',
      platformName: '国网威胜 10kV 进线高精度关口计量装置',
      protocol: 'DL/T 645-2007',
      authType: 'SIMULATED_MOCK',
      syncMode: 'INTERVAL_POLL_5M',
      status: 'ONLINE',
      lastSyncTime: '3分钟前 (2026-09-05 06:10:00)',
      consecutiveFailures: 0,
    },
    {
      id: 'ADAPTER-WEATHER-05',
      type: 'WEATHER_STATION',
      platformName: '华控微气象多合一环境监测仪',
      protocol: 'RS485 Modbus-RTU',
      authType: 'SIMULATED_MOCK',
      syncMode: 'INTERVAL_POLL_5M',
      status: 'ONLINE',
      lastSyncTime: '2分钟前 (2026-09-05 06:11:00)',
      consecutiveFailures: 0,
    },
  ];

  const devices: Device[] = [
    {
      id: 'DEV-PV-INV01',
      siteId: 'SITE-001',
      name: '1# 组串式光伏逆变器 (屋顶1期)',
      type: 'INVERTER',
      manufacturer: '阳光电源',
      model: 'SG320HX-PRO',
      ratedCapacity: '320 kW',
      sourceAdapterId: 'ADAPTER-PV-01',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:12:30',
    },
    {
      id: 'DEV-PV-INV02',
      siteId: 'SITE-001',
      name: '2# 组串式光伏逆变器 (屋顶2期)',
      type: 'INVERTER',
      manufacturer: '阳光电源',
      model: 'SG320HX-PRO',
      ratedCapacity: '320 kW',
      sourceAdapterId: 'ADAPTER-PV-01',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:12:30',
    },
    {
      id: 'DEV-STORAGE-PCS01',
      siteId: 'SITE-001',
      name: '储能变流升压一体机 (PCS)',
      type: 'PCS',
      manufacturer: '时代星云',
      model: 'NEB-500K-HV',
      ratedCapacity: '500 kW',
      sourceAdapterId: 'ADAPTER-STORAGE-02',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:12:45',
    },
    {
      id: 'DEV-STORAGE-BATT01',
      siteId: 'SITE-001',
      name: '磷酸铁锂户外集装箱电池舱',
      type: 'BATTERY_CLUSTER',
      manufacturer: '宁德时代',
      model: 'EnerOne 1000kWh',
      ratedCapacity: '1000 kWh',
      sourceAdapterId: 'ADAPTER-STORAGE-02',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:12:45',
    },
    {
      id: 'DEV-CHARGE-FAST01',
      siteId: 'SITE-001',
      name: '特来电 120kW 双枪直流快速充电桩群',
      type: 'CHARGER_DC',
      manufacturer: '特来电',
      model: 'TELD-DC120-D2',
      ratedCapacity: '120 kW × 6台',
      sourceAdapterId: 'ADAPTER-CHARGER-03',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:11:58',
    },
    {
      id: 'DEV-GRID-METER01',
      siteId: 'SITE-001',
      name: '10kV 进线总降变双向关口电能表',
      type: 'SMART_METER',
      manufacturer: '威胜集团',
      model: 'WSS-DTSD341-9D',
      ratedCapacity: '2000 kVA 配额',
      sourceAdapterId: 'ADAPTER-GRID-04',
      status: 'NORMAL',
      lastDataTime: '2026-09-05 06:10:00',
    },
  ];

  const points: Point[] = [
    {
      id: 'POINT-PV-PAC',
      deviceId: 'DEV-PV-INV01',
      pointName: '光伏有功功率',
      standardCode: 'PV_ACTIVE_POWER_TOTAL',
      thirdPartyField: 'inv_sungrow.p_ac_total',
      unit: 'kW',
      dataType: 'FLOAT',
      lowerLimit: 0,
      upperLimit: 350,
      mappingStatus: 'MAPPED',
      currentValue: 248.6,
      currentQuality: 'NORMAL',
      lastUpdated: '2026-09-05 06:12:30',
    },
    {
      id: 'POINT-BAT-SOC',
      deviceId: 'DEV-STORAGE-BATT01',
      pointName: '电池组当前荷电状态 (SOC)',
      standardCode: 'BATT_SOC_PERCENT',
      thirdPartyField: 'ems_cluster.soc_system',
      unit: '%',
      dataType: 'FLOAT',
      lowerLimit: 5,
      upperLimit: 100,
      mappingStatus: 'MAPPED',
      currentValue: 74.2,
      currentQuality: 'NORMAL',
      lastUpdated: '2026-09-05 06:12:45',
    },
    {
      id: 'POINT-BAT-POWER',
      deviceId: 'DEV-STORAGE-PCS01',
      pointName: '储能变流器实时功率 (+放/-充)',
      standardCode: 'PCS_ACTIVE_POWER',
      thirdPartyField: 'ems_pcs.active_p',
      unit: 'kW',
      dataType: 'FLOAT',
      lowerLimit: -550,
      upperLimit: 550,
      mappingStatus: 'MAPPED',
      currentValue: -180.0, // 谷段充电中
      currentQuality: 'NORMAL',
      lastUpdated: '2026-09-05 06:12:45',
    },
    {
      id: 'POINT-CHG-POWER',
      deviceId: 'DEV-CHARGE-FAST01',
      pointName: '充电站群实时聚合负荷功率',
      standardCode: 'CHARGER_AGGREGATED_LOAD',
      thirdPartyField: 'teld_hub.total_load_kw',
      unit: 'kW',
      dataType: 'FLOAT',
      lowerLimit: 0,
      upperLimit: 720,
      mappingStatus: 'MAPPED',
      currentValue: 142.5,
      currentQuality: 'NORMAL',
      lastUpdated: '2026-09-05 06:11:58',
    },
    {
      id: 'POINT-GRID-LOAD',
      deviceId: 'DEV-GRID-METER01',
      pointName: '10kV 进线变压器总下网负荷',
      standardCode: 'GRID_NET_ACTIVE_POWER',
      thirdPartyField: 'ws_meter.grid_p_in',
      unit: 'kW',
      dataType: 'FLOAT',
      lowerLimit: 0,
      upperLimit: 2000,
      mappingStatus: 'MAPPED',
      currentValue: 564.2,
      currentQuality: 'NORMAL',
      lastUpdated: '2026-09-05 06:10:00',
    },
  ];

  const qualityIssues: DataQualityIssue[] = [
    {
      id: 'QI-20260904-01',
      dimension: 'RANGE_LIMIT',
      dimensionLabel: '越限滤波校验',
      level: 'INFO',
      targetDevice: '园区微气象仪',
      targetPoint: '水平总辐照度',
      discoveredTime: '2026-09-04 12:15:00',
      status: 'RESOLVED',
      resolutionMode: 'AUTO_BACKFILL',
      description: '瞬时云遮导致传感探头突跳，已自动平滑滤波并记录。',
      impactScore: '无负面影响',
    },
  ];

  const revenueSnapshots: RevenueSnapshot[] = [
    {
      id: 'REV-TODAY-ESTIMATE',
      siteId: 'SITE-001',
      dateKey: '今日 (2026-09-05 运行中)',
      calcType: 'ESTIMATE',
      pvRevenue: 1420.5,
      storageArbitrage: 680.0,
      chargingRevenue: 852.0,
      gridPurchaseCost: 1980.2,
      capacityBaseFee: 426.6,
      netComprehensiveRevenue: 545.7,
      dataConfidencePercent: 99.2,
      referencedTariffVersion: 'V1.0',
      qualityFlag: 'NORMAL',
      lastCalcTime: '2026-09-05 06:10:00 (自动每15分钟滚动估算)',
    },
    {
      id: 'REV-YEST-SETTLEMENT-V1',
      siteId: 'SITE-001',
      dateKey: '昨日 (2026-09-04 日终结算)',
      calcType: 'SETTLEMENT',
      pvRevenue: 3840.0,
      storageArbitrage: 1650.0,
      chargingRevenue: 2480.0,
      gridPurchaseCost: 4920.0,
      capacityBaseFee: 1066.0,
      netComprehensiveRevenue: 1984.0,
      dataConfidencePercent: 98.6,
      referencedTariffVersion: 'V1.0',
      qualityFlag: 'NORMAL',
      lastCalcTime: '2026-09-05 00:30:15 (T+1 日终自动归档完成)',
    },
  ];

  const alarms: Alarm[] = [
    {
      id: 'ALM-20260904-01',
      alarmCode: 'ALM-CHG-004',
      source: 'DEVICE',
      isThirdParty: true,
      thirdPartySource: '特来电 TELD-Cloud 物联网网关',
      severity: 'MINOR',
      siteId: 'SITE-001',
      siteName: '示范站',
      deviceId: 'DEV-CHARGE-FAST01',
      deviceName: '特来电 4# 直流充电桩',
      standardCode: 'CHARGER_STATUS_CODE',
      alarmTitle: '充电连接器插拔卡扣微动弹簧磨损提醒',
      description: '桩端电子微动开关动作次数累计达标，插头锁紧到位电阻略有飘移。',
      triggeredAt: '2026-09-04 16:20:00',
      firstOccurrenceTime: '2026-09-04 16:20:00',
      lastOccurrenceTime: '2026-09-04 16:20:00',
      slaDeadlineTime: '2026-09-04 18:20:00 (已按时处置)',
      status: 'CLOSED',
      reason: '现场日常插拔次数累计达到保养阈值，巡检员已现场清理校正。',
      actionTaken: '润滑并复核闭锁电阻正常，现场测试插拔无松动。',
      handledBy: '林志强 (巡检员)',
      traceId: 'TR-20260904-CHG-MAINT',
      evidenceDetails: {
        code: 'WARN_MECH_SPRING_LIFE',
        telemetryValue: '插拔次数: 12,480次 (阈值 12,000)',
        thresholdValue: '≤ 12,000次',
        logSnippet: 'TELD Gun #4 Micro-switch cycle warning',
        impactSummary: '非电气安全故障，已在例行巡检中润滑复位。',
      },
      timeline: [
        { time: '2026-09-04 16:20:00', operator: '特来电平台推送', action: '产生保养预警' },
        { time: '2026-09-04 16:35:10', operator: '陈若涵 (运营)', action: '接单确认并派发巡检' },
        { time: '2026-09-04 17:15:30', operator: '林志强 (巡检员)', action: '现场校正并关闭工单' },
      ],
    },
    {
      id: 'ALM-20260905-02',
      alarmCode: 'ALM-IF-WTH-01',
      source: 'INTERFACE',
      isThirdParty: true,
      thirdPartySource: '阳光电源 iSolarCloud OpenAPI',
      severity: 'WARNING',
      siteId: 'SITE-001',
      siteName: '示范站',
      adapterId: 'ADAPTER-WEATHER-04',
      deviceName: '环境微气象监测网关',
      pointId: 'POINT-ENV-IRRAD',
      standardCode: 'SOLAR_IRRADIATION',
      alarmTitle: '气象云服务 API 响应偶发延迟 (>2.5s)',
      description: '从阳光电源云端请求环境辐射与温湿度接口时，偶发网络握手耗时延长。',
      triggeredAt: '2026-09-05 06:02:10',
      firstOccurrenceTime: '2026-09-05 06:02:10',
      lastOccurrenceTime: '2026-09-05 06:11:45',
      slaDeadlineTime: '2026-09-05 06:32:10 (一般确认限时30m)',
      status: 'PENDING_ACK',
      reason: '第三方天气平台上午峰值请求拥塞，重试后数据仍可正常回传。',
      traceId: 'TR-20260905-API-SLOW',
      evidenceDetails: {
        code: 'HTTP_LATENCY_SLOW_E25',
        telemetryValue: 'RTT 2,680ms (基线 ≤ 500ms)',
        thresholdValue: '≤ 1,500ms',
        logSnippet: 'GET https://api.isolarcloud.com/weather - HTTP 200 (took 2680ms)',
        impactSummary: '仅影响气象辅测数据刷新频率，暂不影响光伏发电计量主线。',
      },
      agentEventId: 'AGENT-EVT-01',
      agentAnalysisStatus: 'ANALYZED',
      agentSuggestion: '网络偶发波动，建议设置适配器自适应延长超时窗口至 5s，观察 2 个周期。',
      timeline: [
        { time: '2026-09-05 06:02:10', operator: '接口健康监测器', action: '触发响应延迟预警' },
      ],
    },
    {
      id: 'ALM-20260905-03',
      alarmCode: 'ALM-TH-DEM-01',
      source: 'THRESHOLD',
      isThirdParty: false,
      severity: 'MAJOR',
      siteId: 'SITE-001',
      siteName: '示范站',
      deviceId: 'DEV-GRID-METER01',
      deviceName: '10kV 进线变电总表',
      pointId: 'POINT-GRID-LOAD',
      standardCode: 'GRID_NET_ACTIVE_POWER',
      alarmTitle: '变压器瞬态视在功率触及合同需量 82.5% (预警线)',
      description: '多台直流快充桩同时大功率起充，进线负荷瞬态攀升至 1650 kVA，需警惕容量电费越限违章。',
      triggeredAt: '2026-09-05 05:48:30',
      firstOccurrenceTime: '2026-09-05 05:48:30',
      lastOccurrenceTime: '2026-09-05 06:08:20',
      slaDeadlineTime: '2026-09-05 06:18:30 (一般确认限时30m)',
      status: 'PROCESSING',
      reason: '早高峰通勤前重卡及网约车集中进站快充，叠加上网光伏尚未爬坡完毕。',
      handledBy: '陈若涵 (运营人员)',
      traceId: 'TR-20260905-DEMAND-WARN',
      evidenceDetails: {
        code: 'DEMAND_PRE_ALARM_80PCT',
        telemetryValue: '当前视在功率: 1,650 kVA / 需量利用率 82.5%',
        thresholdValue: '安全阈值 ≤ 80.0% (1,600 kVA)',
        logSnippet: 'Meter #1 demand active load 1650kW peak recorded in 15min rolling interval',
        impactSummary: '若连续 2 个窗口超 90%，将产生月度基本电费惩罚性倍增风险。',
      },
      agentAnalysisStatus: 'ANALYZING',
      agentSuggestion: '建议动态下发充电桩群柔性功率限制指令，暂扣单枪上限至 90kW。',
      timeline: [
        { time: '2026-09-05 05:48:30', operator: '电网需量监测模块', action: '触发需量 80% 越限预警' },
        { time: '2026-09-05 05:54:12', operator: '陈若涵 (运营人员)', action: '确认告警并启动削峰调度' },
      ],
    },
    {
      id: 'ALM-20260905-04',
      alarmCode: 'ALM-DQ-PV-01',
      source: 'DATA_QUALITY',
      isThirdParty: false,
      severity: 'MINOR',
      siteId: 'SITE-001',
      siteName: '示范站',
      deviceId: 'DEV-PV-INV01',
      deviceName: '1# 阳光电源 320kW 组串式逆变器',
      pointId: 'POINT-PV-POWER',
      standardCode: 'INV_ACTIVE_POWER',
      alarmTitle: '逆变器 4# 直流支路输入电流偶发跳变异常',
      description: '测点检测到持续 2 个采样点电流跳变为 0 后自动回升，疑似前级汇流箱保险偶发虚接。',
      triggeredAt: '2026-09-05 05:55:00',
      firstOccurrenceTime: '2026-09-05 05:55:00',
      lastOccurrenceTime: '2026-09-05 06:05:00',
      slaDeadlineTime: '2026-09-05 06:25:00 (一般确认限时30m)',
      status: 'PENDING_ACK',
      reason: '数据质量连续性偶发断续，已在质量中心生成置信度降级标记。',
      traceId: 'TR-20260905-DQ-MUTATION',
      qualityIssueId: 'QI-PV-MUTATION-02',
      qualityLevel: 'SUSPICIOUS',
      evidenceDetails: {
        code: 'DQ_SUDDEN_ZERO_DROP',
        telemetryValue: 'PV String 4 Current: 0.0A (突降持续 30s)',
        thresholdValue: '正常运行带载 ≥ 12.5A',
        logSnippet: 'Rule: Point sudden zero drop without sunshine decrease',
        impactSummary: '局部支路损失约 3.2 kWh 发电量，数据置信度微幅下调 0.5%。',
      },
      agentAnalysisStatus: 'ANALYZED',
      agentSuggestion: '建议在明日日常巡检中带上钳形电流表对 4# 汇流端子进行红外测温。',
      timeline: [
        { time: '2026-09-05 05:55:00', operator: '数据质量检测规则', action: '检测到突变并标记为可疑' },
      ],
    },
  ];

  const agentEvents: AgentEvent[] = [
    {
      id: 'AGENT-EVT-01',
      agentPriority: 'P3',
      priority: 'LOW',
      title: '早谷充放电排程合理性复核与日报建议',
      agentType: 'OPERATIONS_REVENUE',
      agentName: '运营收益 Agent',
      targetObject: '今日早谷时段储能充电排程',
      ruleEvidence: [
        '当前有效计费版本: Tariff-V1.0 (低谷电价 0.310 元/kWh)',
        '当前储能实际 SOC: 74.2% (建议经济充程区间: ≤ 90%)',
        '光伏上午出力实测爬坡正常，日照辐照度 850 W/m²',
        '数据质量维度校验: 完整性 100%、连续性 99.8%',
      ],
      ruleMatched: 'RULE-REV-TOU-OPT-01 (峰谷价差套利空间校验 > 0.85元/kWh)',
      triggerTime: '2026-09-05 05:40:00',
      sla: '2026-09-05 08:30:00 (早峰前完成)',
      status: 'ARCHIVED',
      traceId: 'TR-AGENT-20260905-054000-REV1',
      sourcePage: '运营收益中心',
      degradedStatus: false,
      aiSummary: '【辅助研判】预计上午 08:30 进入第一高峰段，储能当前电量可在高峰期放电 320 kWh，产生约 256 元峰谷套利价差。建议保持既定充放电策略并纳入综合日报草稿。',
      templateSummary: '【规则模板】低谷充电量符合预设策略，核算价差符合预期，建议保持既定充放电排程。',
      confidenceScore: 95,
      revenueImpactEstimate: '+256.00 元',
      suggestedAction: '人工复核通过，纳入早班综合运营日报摘要草稿。',
      archiveNote: '早谷充放电正常执行，早班运营人员已确认并自动纳入结算报表。',
      actionHistory: [
        {
          time: '2026-09-05 05:40:00',
          operator: '运营收益 Agent 引擎',
          action: '生成辅助诊断与收益预测',
          note: '基于电价 V1.0 与实时 SOC 综合研判，置信度 95%',
        },
        {
          time: '2026-09-05 05:45:10',
          operator: '陈若涵 (运营人员)',
          action: '确认归档',
          note: '采纳建议，无须变更既定策略',
        },
      ],
    },
    {
      id: 'AGENT-EVT-03',
      agentPriority: 'P2',
      priority: 'MEDIUM',
      title: '环境气象 API 响应偶发延迟原因诊断与补采排程',
      agentType: 'DATA_INGESTION',
      agentName: '数据接入 Agent',
      targetObject: 'ADAPTER-WEATHER-04 (阳光电源气象云 API)',
      ruleEvidence: [
        'API 响应时延突增: 2,680ms (基线 ≤ 500ms)',
        '第三方平台接口返回 HTTP 200，但数据包耗时偏长',
        '对应气象测点 POINT-ENV-IRRAD 刷新延迟已消除',
      ],
      ruleMatched: 'RULE-INGEST-API-LATENCY-03 (第三方接口偶发网络抖动判定)',
      triggerTime: '2026-09-05 06:05:00',
      sla: '2026-09-05 08:00:00',
      status: 'AWAITING_DECISION',
      traceId: 'TR-AGENT-20260905-060500-WTH',
      sourcePage: '数据接入与治理',
      degradedStatus: false,
      aiSummary: '【辅助研判】第三方气象云接口在清晨出现短暂通信拥塞，目前通信状态已自动恢复正常。建议暂缓人工干预，继续观察 2 个抓取周期，若再次抖动则自适应延长超时阈值至 5s。',
      templateSummary: '【规则模板】检测到第三方接口通信时延升高，接口已自动恢复正常，建议暂缓处置并持续监控。',
      confidenceScore: 88,
      revenueImpactEstimate: '暂无直接经济损失 (光伏辐照辅助测点)',
      suggestedAction: '建议人工审查后执行【暂缓】观察，无需现场派工。',
      relatedAlarmCode: 'ALM-IF-WTH-01',
      relatedAdapterId: 'ADAPTER-WEATHER-04',
      actionHistory: [
        {
          time: '2026-09-05 06:05:00',
          operator: '数据接入 Agent 引擎',
          action: '分析完成',
          note: '时延突增后快速回落，判定为外网抖动，建议暂缓人工下发工单',
        },
      ],
    },
    {
      id: 'AGENT-EVT-04',
      agentPriority: 'P3',
      priority: 'LOW',
      title: '1# 阳光逆变器 4# 支路电流偶发跳变隐患排查建议',
      agentType: 'PATROL_MAINTENANCE',
      agentName: '运维巡检 Agent',
      targetObject: 'DEV-PV-INV01 (1# 阳光电源 320kW 组串式逆变器)',
      ruleEvidence: [
        '测点跳变特征: 持续 2 个采样点电流归 0 (30秒) 后回升',
        '同时段光伏环境总辐照度保持 850 W/m² (排除云遮)',
        '数据质量评级已降为【可疑 (SUSPICIOUS)】',
      ],
      ruleMatched: 'RULE-OPS-PV-MUTATION-02 (光伏直流侧接线虚接或保险微动)',
      triggerTime: '2026-09-05 06:00:00',
      sla: '2026-09-05 12:00:00 (午间巡检前完成确认)',
      status: 'AWAITING_DECISION',
      traceId: 'TR-AGENT-20260905-060000-PV1',
      sourcePage: '微电网告警中心',
      degradedStatus: false,
      aiSummary: '【辅助研判】逆变器直流 4# 支路在无光照突降情况下电流瞬时归零，极可能是前级汇流接线盒接触电阻异常或熔断器松动。建议由运营人员确认后派发现场巡检任务，带红外测温枪就地检测端子排。',
      templateSummary: '【规则模板】直流支路电流突跳，疑似接触不良，建议派发就地巡检并测量接线温度。',
      confidenceScore: 89,
      revenueImpactEstimate: '日发电损失约 -3.20 元',
      suggestedAction: '确认并生成日常专项巡检任务，安排巡检员林志强午间复测。',
      relatedAlarmCode: 'ALM-DQ-PV-01',
      relatedQualityIssueId: 'QI-PV-MUTATION-02',
      actionHistory: [
        {
          time: '2026-09-05 06:00:00',
          operator: '运维巡检 Agent 引擎',
          action: '隐患特征比对完成',
          note: '关联数据质量问题 QI-PV-MUTATION-02，等待运营决策',
        },
      ],
    },
  ];

  const patrolTasks: PatrolTask[] = [
    {
      id: 'TASK-PATROL-01',
      planId: 'PLAN-DAILY-01',
      taskCode: 'PATROL-20260905-D1',
      title: '示范站微电网核心设备日常例巡',
      description: '例行巡检光伏逆变器1#、2#组串、时代星云储能变流升压一体机及120kW直流快充桩群电气接线与散热状态。',
      planDeadline: '2026-09-05 18:00',
      assignee: '林志强',
      deviceList: ['光伏逆变器1#', '光伏逆变器2#', '储能变流一体机', '储能集装箱', '120kW双枪充电桩群'],
      plannedDate: '2026-09-05',
      status: 'PENDING_START',
      isOffline: false,
      totalItems: 4,
      hasAbnormality: false,
      checkItems: [
        {
          id: 'CI-01',
          itemName: '时代星云 500kW PCS 变流柜主断路器状态检查',
          method: '目视与就地仪表核验',
          standard: '断路器闭合状态正常，就地指示灯常绿，无焦糊异味',
          result: 'NORMAL',
        },
        {
          id: 'CI-02',
          itemName: 'CATL 储能电池集装箱空调与热管理管路温差',
          method: '红外测温枪实测',
          standard: '进回风温差在 3~5℃ 范围内，冷却水泵运行无异常震动',
          result: 'NORMAL',
        },
        {
          id: 'CI-03',
          itemName: 'EMS 现场前置工控机 RS485/以太网通信接头',
          method: '线缆拔插紧固与指示灯核查',
          standard: 'RJ45 与端子排连接牢固，TX/RX 闪烁节拍与轮询一致',
          result: 'NORMAL',
        },
        {
          id: 'CI-04',
          itemName: '1#、2# 屋顶光伏组串逆变器交流并网箱防雷开关',
          method: '防雷器视窗检查',
          standard: '防雷视窗呈绿色，接地扁铁阻抗 < 4Ω',
          result: 'NORMAL',
        },
      ],
    },
  ];

  const workOrders: WorkOrder[] = [];

  const auditLogs: AuditLog[] = [
    {
      id: 'LOG-P18-001',
      timestamp: '2026-09-05 06:00:00',
      role: 'ADMIN',
      operatorName: '张宇轩',
      targetObject: '全链路微服务健康诊断',
      action: '触发平台健康自检',
      oldState: 'CHECKING',
      newState: 'HEALTHY',
      reason: '执行前端 SPA、模拟网关、本地持久化、实时流、5 类物理适配器与 Agent 综合健康诊断',
      traceId: 'TR-P18-HEALTH-DIAG-20260905-060000',
      result: 'SUCCESS',
      sourcePage: '/admin/health',
    },
    {
      id: 'LOG-P17-001',
      timestamp: '2026-09-04 11:30:00',
      role: 'ADMIN',
      operatorName: '张宇轩',
      targetObject: 'OPERATOR 角色策略矩阵',
      action: '核验两票制防舞弊互斥策略',
      oldState: 'VERIFYING',
      newState: 'ENFORCED',
      reason: '策略校验：确保 OPERATOR 角色仅有电价起草权 (tariff_submit)，严禁授予电价生效审批权 (tariff_approve)',
      traceId: 'TR-P17-ROLE-MATRIX-20260904-113000',
      result: 'SUCCESS',
      sourcePage: '/admin/roles',
    },
    {
      id: 'LOG-P16-001',
      timestamp: '2026-09-04 10:00:00',
      role: 'ADMIN',
      operatorName: '张宇轩',
      targetObject: 'USR-INSP-03 (林志强)',
      action: '分配现场巡检特种作业权限',
      oldState: 'PENDING_AUTH',
      newState: 'AUTHORIZED',
      reason: '核验特种高压电工作业证与登高作业资质，授予现场巡检执行与工单处理权限',
      traceId: 'TR-P16-USER-MANAGE-20260904-100000',
      result: 'SUCCESS',
      sourcePage: '/admin/users',
    },
    {
      id: 'LOG-P15-001',
      timestamp: '2026-09-05 01:15:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'RPT-20260904-001',
      action: '综合运营日报归档',
      oldState: 'GENERATING',
      newState: 'COMPLETED',
      reason: '全站综合运营日报数据校验完成，置信度 99.2%，完成财务级归档',
      traceId: 'TR-P15-REPORT-ARCHIVE-20260905-011500',
      result: 'SUCCESS',
      sourcePage: '/reports',
      relatedVersion: 'V1.0',
    },
    {
      id: 'LOG-P14-001',
      timestamp: '2026-09-05 02:10:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'RC-20260905-001 (重算批次)',
      action: '发起收益偏差回溯重算',
      oldState: 'ESTIMATE',
      newState: 'RECALCULATED',
      reason: '修复昨日储能充放电计量缺失数据后，触发 T+1 收益全量重算生成 V2 快照',
      traceId: 'TR-P14-REVENUE-RECALC-20260905-021000',
      result: 'SUCCESS',
      sourcePage: '/revenue',
      relatedVersion: 'Snapshot V2',
    },
    {
      id: 'LOG-P13-001',
      timestamp: '2026-09-04 17:30:00',
      role: 'ADMIN',
      operatorName: '电子存证服务',
      targetObject: 'REC-20260904-001',
      action: '巡检记录数字存证上链',
      oldState: 'GENERATED',
      newState: 'ARCHIVED',
      reason: '生成不可篡改哈希电子凭证，并加盖中节能示范站防篡改数字存证戳',
      traceId: 'TR-P13-RECORD-ARCHIVE-20260904-173000',
      result: 'SUCCESS',
      sourcePage: '/operations/records',
    },
    {
      id: 'LOG-P12-001',
      timestamp: '2026-09-04 17:15:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'WO-20260904-001',
      action: '整改工单终审复核归档',
      oldState: 'RESOLVED',
      newState: 'CLOSED',
      reason: '现场更换储能通信交换机端口已闭环，测试 30 分钟无丢包，复核通过',
      traceId: 'TR-P12-WO-REVIEW-20260904-171500',
      result: 'SUCCESS',
      sourcePage: '/operations/work-orders',
    },
    {
      id: 'LOG-P11-001',
      timestamp: '2026-09-04 09:35:00',
      role: 'INSPECTOR',
      operatorName: '林志强',
      targetObject: '现场点检项 PCS-01-T01',
      action: '移动终端 GPS 打卡提交',
      oldState: 'UNCHECKED',
      newState: 'NORMAL',
      reason: '现场巡检点检完成，GPS 坐标校验经纬度一致（东经 117.65° 北纬 24.51°）',
      traceId: 'TR-P11-MOBILE-CHECKIN-20260904-093500',
      result: 'SUCCESS',
      sourcePage: '/mobile/tasks',
    },
    {
      id: 'LOG-P10-001',
      timestamp: '2026-09-04 08:00:00',
      role: 'ADMIN',
      operatorName: '巡检调度引擎',
      targetObject: 'TASK-20260904-001',
      action: '按计划自动生成并派发任务',
      oldState: 'PENDING',
      newState: 'IN_PROGRESS',
      reason: '根据 PLAN-2026-W01 计划下发高压配电与储能周检任务给巡检员林志强',
      traceId: 'TR-P10-TASK-DISPATCH-20260904-080000',
      result: 'SUCCESS',
      sourcePage: '/operations/tasks',
    },
    {
      id: 'LOG-P09-001',
      timestamp: '2026-09-01 09:00:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'PLAN-2026-W01',
      action: '发布周度巡检计划',
      oldState: 'DRAFT',
      newState: 'PUBLISHED',
      reason: '制定示范站 2026年9月第1周高低压设备常规周检计划并生效排程',
      traceId: 'TR-P09-PLAN-GEN-20260901-090000',
      result: 'SUCCESS',
      sourcePage: '/operations/plans',
    },
    {
      id: 'LOG-P08-001',
      timestamp: '2026-09-05 05:46:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'Agent 决策推理引擎',
      action: '采纳 Agent 故障排查建议',
      oldState: 'RECOMMENDED',
      newState: 'ADOPTED',
      reason: '采纳数据接入 Agent 建议：派发现场特种工程工单对储能柜现场网关进行硬重启',
      traceId: 'TR-P08-AGENT-DECISION-20260905-054500',
      result: 'SUCCESS',
      sourcePage: '/agent-hub',
    },
    {
      id: 'LOG-P07-001',
      timestamp: '2026-09-05 05:45:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: 'ALM-STORAGE-COMM-01',
      action: '人工确认并抑制告警',
      oldState: 'CRITICAL',
      newState: 'ACKNOWLEDGED',
      reason: '核实现场储能 EMS 通信连续中断，在 SLA 响应时限内人工确认并联动派单',
      traceId: 'TR-P07-ALARM-ACK-20260905-054500',
      result: 'SUCCESS',
      sourcePage: '/alarms',
    },
    {
      id: 'LOG-P06-001',
      timestamp: '2026-09-04 14:20:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: '1# 储能双向变流器 PCS-01',
      action: '工况自检与台账更新',
      oldState: 'IDLE',
      newState: 'RUNNING',
      reason: '日常台账工况巡检，变流器绝缘阻抗与温升正常',
      traceId: 'TR-P06-DEVICE-STATUS-20260904-142000',
      result: 'SUCCESS',
      sourcePage: '/monitor/devices',
    },
    {
      id: 'LOG-P05-001',
      timestamp: '2026-09-05 01:00:00',
      role: 'ADMIN',
      operatorName: '系统能效监控服务',
      targetObject: '10kV 进线母线功率流向',
      action: '功率平衡限值校验',
      oldState: 'VERIFYING',
      newState: 'BALANCED',
      reason: '全站能量平衡误差率 0.32% (< 1.0% 阈值)，流向拓扑正常',
      traceId: 'TR-P05-FLOW-EQUILIBRIUM-20260905-010000',
      result: 'SUCCESS',
      sourcePage: '/monitor/flow',
    },
    {
      id: 'LOG-P04-001',
      timestamp: '2026-09-04 18:00:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: '微电网全景拓扑图',
      action: '切换调度运行策略',
      oldState: 'PEAK_CLIPPING',
      newState: 'ECONOMIC_ARBITRAGE',
      reason: '晚间电价进入平段与低谷，自动执行储能谷充峰放经济调度',
      traceId: 'TR-P04-SCREEN-DISPATCH-20260904-180000',
      result: 'SUCCESS',
      sourcePage: '/screen',
    },
    {
      id: 'LOG-P03-001',
      timestamp: '2026-09-04 16:30:00',
      role: 'ADMIN',
      operatorName: '张宇轩',
      targetObject: '电价版本 V1.0',
      action: '二次授权生效',
      oldState: 'PENDING_APPROVAL',
      newState: 'EFFECTIVE',
      reason: '核实发改委大工业分时通知文号一致（闽发改规[2025]18号），符合两票制二次授权规范，批准生效',
      traceId: 'TR-P03-TARIFF-AUTH-20260904-163000',
      result: 'SUCCESS',
      sourcePage: '/tariffs',
      relatedVersion: 'V1.0',
    },
  ];

  return {
    adapters,
    devices,
    points,
    qualityIssues,
    revenueSnapshots,
    recalcBatches: [] as RecalculationBatch[],
    alarms,
    agentEvents,
    patrolPlans: MOCK_PATROL_PLANS,
    patrolTasks,
    patrolRecords: MOCK_PATROL_RECORDS,
    workOrders,
    auditLogs,
  };
}

// 场景 B 状态（储能 EMS 异常闭环）
export function getScenarioBState() {
  const base = getScenarioAState();

  // 1. 储能 EMS 适配器状态变为 RETRYING (连续3次超时)
  const adapters: IntegrationAdapter[] = base.adapters.map((ad) => {
    if (ad.id === 'ADAPTER-STORAGE-02') {
      return {
        ...ad,
        status: 'RETRYING' as const,
        lastSyncTime: '35分钟前 (2026-09-05 05:37:12)',
        consecutiveFailures: 3,
        errorDetail: 'TCP/IP 连接建立超时 (10054 Connection Reset)，连续 3 个上报周期无心跳帧响应。',
      };
    }
    return ad;
  });

  // 2. 储能设备状态更新为 ALARM / SUSPICIOUS
  const devices: Device[] = base.devices.map((dev) => {
    if (dev.id.includes('STORAGE')) {
      return {
        ...dev,
        status: 'ALARM' as const,
        lastDataTime: '2026-09-05 05:37:12 (数据中断)',
      };
    }
    return dev;
  });

  // 3. 点位质量更新为 ANOMALY
  const points: Point[] = base.points.map((pt) => {
    if (pt.id.includes('BAT')) {
      return {
        ...pt,
        currentQuality: 'ANOMALY' as const,
        lastUpdated: '2026-09-05 05:37:12',
      };
    }
    return pt;
  });

  // 4. 数据质量问题新增一个 CRITICAL
  const qualityIssues: DataQualityIssue[] = [
    {
      id: 'QI-STORAGE-LOST-01',
      dimension: 'CONTINUITY',
      dimensionLabel: '数据连续性中断',
      level: 'CRITICAL',
      targetDevice: '时代星云 CATL-Nebula EMS',
      targetPoint: '储能充放电功率 / SOC 荷电状态',
      discoveredTime: '2026-09-05 05:42:00',
      status: 'PENDING',
      resolutionMode: 'MANUAL_INTERVENTION',
      description: '储能系统连续丢失 3 个采集窗口，无法获取实时充放电与电芯温控，已阻塞财务精准计量。',
      impactScore: '影响昨日结算置信度 (降至 71.4%)，当前综合收益存在结算风险提示',
    },
    ...base.qualityIssues,
  ];

  // 5. 生成紧急告警 (SLA 截止 15 分钟确认 / 30 分钟处置)
  const alarms: Alarm[] = [
    {
      id: 'ALM-STORAGE-COMM-01',
      alarmCode: 'ALM-EMS-CRIT-01',
      source: 'INTERFACE',
      isThirdParty: false,
      severity: 'CRITICAL',
      siteId: 'SITE-001',
      siteName: '示范站',
      adapterId: 'ADAPTER-STORAGE-02',
      deviceId: 'DEV-STORAGE-PCS01',
      deviceName: '时代星云储能 EMS 通信前置机',
      pointId: 'POINT-BAT-POWER',
      standardCode: 'PCS_ACTIVE_POWER',
      alarmTitle: '储能 EMS 连续 3 个采集周期无心跳响应 (紧急通信中断)',
      description: '时代星云储能预制舱通信前置机与中控平台握手失败，丢失下行遥测与电芯温控，削峰放电被紧急阻断。',
      triggeredAt: '2026-09-05 05:37:12',
      firstOccurrenceTime: '2026-09-05 05:37:12',
      lastOccurrenceTime: '2026-09-05 06:12:45',
      slaDeadlineTime: '2026-09-05 06:07:12 (处置限时 30m [已超时])',
      slaConfirmDeadline: '2026-09-05 05:52:12',
      slaHandleDeadline: '2026-09-05 06:07:12',
      status: 'PROCESSING',
      reason: '前置交换机本地端口指示灯疑似异常或电源跳脱，导致 Modbus/TCP 握手超时。',
      handledBy: '陈若涵 (运营人员)',
      traceId: 'TR-20260905-COMM-FAIL',
      qualityIssueId: 'QI-STORAGE-LOST-01',
      qualityLevel: 'ANOMALY',
      agentEventId: 'AGENT-EVT-STORAGE-02',
      agentAnalysisStatus: 'AWAITING_DECISION',
      agentSuggestion: '判断为交换机供电中断，建议立即派发现场特巡工单核实网络跳线，恢复后进行数据补采与收益 V2 重算。',
      agentConfidenceScore: 92,
      isOverdue: true,
      evidenceDetails: {
        code: 'ERR_MODBUS_TCP_TIMEOUT_3X',
        telemetryValue: '心跳中断持续 35min / 遥测丢包率 100%',
        thresholdValue: '心跳响应周期 ≤ 15s (超时阈值 30s)',
        logSnippet: '[ADAPTER-STORAGE-02] Modbus/TCP connection timeout to 192.168.10.240:502 after 3 retry attempts',
        impactSummary: '储能削峰放电冻结，昨日套利核算置信度下浮至 71.4%，阻断 T+1 日终结算。',
      },
      timeline: [
        { time: '2026-09-05 05:37:12', operator: '适配器健康守护', action: '触发通信中断紧急告警' },
        { time: '2026-09-05 05:41:00', operator: '陈若涵 (运营人员)', action: '接单响应确认，SLA 进入处置阶段' },
        { time: '2026-09-05 05:43:10', operator: 'Agent 研判引擎', action: '生成网络断线根因分析与特巡工单建议' },
        { time: '2026-09-05 06:07:12', operator: 'SLA 监管模块', action: '触发处置超时预警 (已超时 >8分钟)' },
      ],
    },
    ...base.alarms,
  ];

  // 6. 数据接入 Agent 与运营巡检 Agent 给出断线、补采与工单建议
  const agentEvents: AgentEvent[] = [
    {
      id: 'AGENT-EVT-STORAGE-02',
      agentPriority: 'P1',
      priority: 'HIGH',
      title: '储能 EMS 前置通信链路中断诊断与特巡消缺建议',
      agentType: 'DATA_INGESTION',
      agentName: '数据接入 Agent',
      targetObject: 'ADAPTER-STORAGE-02 (时代星云 EMS 网关)',
      ruleEvidence: [
        '连续 3 次 Modbus/TCP 握手超时 (阈值: ≥ 3 次失败)',
        '心跳断开持续时长: 35 分钟 (远超告警阈值 15 分钟)',
        '测点状态: POINT-BAT-POWER 遥测断流，质量判定为 ANOMALY (异常)',
        '关联业务影响: 储能削峰放电冻结，昨日套利核算置信度骤降至 71.4%',
      ],
      ruleMatched: 'RULE-INGEST-STORAGE-OFFLINE-01 (储能 EMS 关键数据源通信阻断判定)',
      triggerTime: '2026-09-05 05:42:15',
      sla: '2026-09-05 06:12:15 (紧急事件限时 30m 决策)',
      status: 'AWAITING_DECISION',
      traceId: 'TR-20260905-COMM-FAIL',
      sourcePage: '数据接入与治理',
      degradedStatus: false,
      aiSummary: '【辅助研判】监测到时代星云储能预制舱 EMS 链路中断 35 分钟，自动软重试 3 次均因连接重置失败。特征显示下行遥测与电芯温控完全丢失，判断为前置工业交换机供电跳脱或光电转换模块硬件异常。建议立即由运营人员确认并向现场巡检员林志强生成消缺工单，恢复网络后启动断点数据补采并触发收益 V2 重算。',
      templateSummary: '【规则模板】储能 EMS 通信超时连续 3 次，心跳断开 >30 分钟，建议派发现场特巡工单核查交换机，并准备断点补采。',
      confidenceScore: 92,
      revenueImpactEstimate: '储能削峰放电受阻，预估套利偏差 -320.00 元/日',
      suggestedAction: '人工确认后派发整改工单，安排现场巡检员林志强紧急消缺。',
      relatedAlarmCode: 'ALM-STORAGE-COMM-01',
      relatedAdapterId: 'ADAPTER-STORAGE-02',
      relatedQualityIssueId: 'QI-STORAGE-LOST-01',
      actionHistory: [
        {
          time: '2026-09-05 05:42:15',
          operator: '数据接入 Agent 引擎',
          action: '生成辅助诊断与决策建议',
          note: '依据 Modbus/TCP 失败特征及质量关联规则，置信度 92%',
        },
      ],
    },
    {
      id: 'AGENT-EVT-STORAGE-05',
      agentPriority: 'P1',
      priority: 'HIGH',
      title: '储能套利数据置信度预警 (71.4%) 与 T+1 结算重算建议',
      agentType: 'OPERATIONS_REVENUE',
      agentName: '运营收益 Agent',
      targetObject: '昨日 (2026-09-04) 储能峰谷套利日终结算',
      ruleEvidence: [
        '数据质量门禁: 数据置信度仅 71.4% (财务核定门禁要求 ≥ 95.0%)',
        '关联缺失点位: 储能电池舱充放电有功功率缺失 35 分钟',
        '计费版本有效引用: Tariff-V1.0 (尖峰 1.500 / 深谷 0.200)',
      ],
      ruleMatched: 'RULE-REV-CONFIDENCE-GATE-01 (财务结算置信度阻断门禁)',
      triggerTime: '2026-09-05 05:50:00',
      sla: '2026-09-05 10:00:00 (日终结算复核截止)',
      status: 'AWAITING_DECISION',
      traceId: 'TR-AGENT-20260905-055000-REV-GATE',
      sourcePage: '运营收益中心',
      degradedStatus: false,
      aiSummary: '【辅助研判】因储能 EMS 现场网关断线，昨日结算数据置信度低于 95% 财务门禁，系统已自动标记结算风险提示。建议待现场完成设备通信恢复及历史断点补采后，由运营人员在收益中心发起 T+1 收益重算生成 V2.0 归档。',
      templateSummary: '【规则模板】结算置信度 71.4% 未达 95% 门禁，当前结算挂起，需待数据补采后执行 T+1 重算。',
      confidenceScore: 94,
      revenueImpactEstimate: '结算待修正差异约 +320.00 元',
      suggestedAction: '建议暂缓日终正式出账，等待现场网络恢复与数据补采完成。',
      relatedAlarmCode: 'ALM-STORAGE-COMM-01',
      relatedTariffVersion: 'V1.0',
      actionHistory: [
        {
          time: '2026-09-05 05:50:00',
          operator: '运营收益 Agent 引擎',
          action: '置信度门禁触发告警',
          note: '置信度低于 95% 触发财务结算风险隔离，建议人工审查并暂缓出账',
        },
      ],
    },
    ...base.agentEvents,
  ];

  // 7. 巡检任务更新（包含离线与异常处置）
  const patrolTasks: PatrolTask[] = [
    {
      id: 'TASK-PATROL-01',
      planId: 'PLAN-DAILY-01',
      taskCode: 'PATROL-20260905-D1',
      title: '时代星云储能预制舱通信异常应急排查',
      description: '联动 Agent Hub 派发，巡检员现场核查 EMS 前置网关网线连接、就地指示灯及 Modbus 链路。',
      planDeadline: '2026-09-05 10:30',
      assignee: '林志强',
      deviceList: ['时代星云储能 EMS 网关', '储能变流一体机', '储能电池舱', '光伏逆变器'],
      plannedDate: '2026-09-05',
      status: 'IN_PROGRESS',
      isOffline: true, // 巡检员现场处于局域无网环境，支持离线暂存
      offlineItemsCompleted: 2,
      totalItems: 4,
      hasAbnormality: true,
      linkedAlarmId: 'ALM-STORAGE-COMM-01',
      linkedWorkOrderId: 'WO-20260905-001',
      checkItems: [
        {
          id: 'CI-01',
          itemName: '时代星云 500kW PCS 变流柜主断路器状态检查',
          method: '目视与就地仪表核验',
          standard: '断路器闭合状态正常，就地指示灯常绿，无焦糊异味',
          result: 'NORMAL',
        },
        {
          id: 'CI-02',
          itemName: 'EMS 现场前置工控机 RS485/以太网通信接头',
          method: '线缆拔插紧固与指示灯核查',
          standard: 'RJ45 与端子排连接牢固，TX/RX 闪烁节拍与轮询一致',
          result: 'ANOMALY',
        },
        {
          id: 'CI-03',
          itemName: 'CATL 储能电池集装箱空调与热管理管路温差',
          method: '红外测温枪实测',
          standard: '进回风温差在 3~5℃ 范围内，冷却水泵运行无异常震动',
          result: 'NORMAL',
        },
        {
          id: 'CI-04',
          itemName: '1#、2# 屋顶光伏组串逆变器交流并网箱防雷开关',
          method: '防雷器视窗检查',
          standard: '防雷视窗呈绿色，接地扁铁阻抗 < 4Ω',
          result: 'NORMAL',
        },
      ],
    },
  ];

  // 8. 整改工单生成
  const workOrders: WorkOrder[] = [
    {
      id: 'WO-20260905-001',
      orderCode: 'WO-20260905-001',
      title: '时代星云储能 EMS 现场网关连通性排查与恢复',
      source: 'AGENT_RECOMMENDATION',
      sourceId: 'AGENT-EVT-STORAGE-02',
      priority: 'CRITICAL',
      assignee: '林志强 (巡检员)',
      status: 'IN_PROGRESS',
      issueDescription: '平台监测到储能 EMS 连续 3 个上报周期通信无响应，疑似现场工业级交换机死机或光纤收发器松脱。',
      handlingEvidence: '【现场排查中】巡检员已到达现场储能预制舱二次设备间，确认交换机电源指示灯黄闪。',
      handledTime: undefined,
      reviewer: '陈若涵 (运营人员)',
    },
  ];

  // 9. 昨日结算收益由于缺失数据，置信度降至 71.4%，提示风险并支持发起 V2 重算
  const revenueSnapshots: RevenueSnapshot[] = [
    {
      ...base.revenueSnapshots[0],
      dataConfidencePercent: 82.5,
      qualityFlag: 'RISK_WARNING',
      warningMessage: '储能实时遥测数据缺失，今日当前收益包含推算模拟估值，不可作为财务对账依据。',
    },
    {
      ...base.revenueSnapshots[1],
      dataConfidencePercent: 71.4,
      qualityFlag: 'RISK_WARNING',
      warningMessage: '昨日 22:00-24:00 谷段储能充电计量丢失 2 个批次，收益置信度低于 85% 预警阈值。需补采校验后重新结算。',
    },
  ];

  const auditLogs: AuditLog[] = [
    {
      id: 'LOG-B-001',
      timestamp: '2026-09-05 05:45:00',
      role: 'OPERATOR',
      operatorName: '陈若涵',
      targetObject: '工单 WO-20260905-001',
      action: '派发整改工单',
      oldState: 'AWAITING_DECISION',
      newState: 'IN_PROGRESS',
      reason: '响应数据接入 Agent 建议，现场派发特种维护工单排查储能通信故障',
      traceId: 'TR-AGENT-DISPATCH-20260905-054500',
    },
    {
      id: 'LOG-B-002',
      timestamp: '2026-09-05 05:42:00',
      role: 'ADMIN',
      operatorName: '系统告警风控中心',
      targetObject: 'ALM-STORAGE-COMM-01',
      action: '触发紧急告警',
      oldState: 'NORMAL',
      newState: 'CRITICAL',
      reason: '储能 EMS 连续 3 个周期丢失心跳，触发 SLA 15分钟确认规则',
      traceId: 'TR-ALM-TRIGGER-20260905-054200',
    },
    ...base.auditLogs,
  ];

  return {
    adapters,
    devices,
    points,
    qualityIssues,
    revenueSnapshots,
    recalcBatches: [] as RecalculationBatch[],
    alarms,
    agentEvents,
    patrolPlans: MOCK_PATROL_PLANS,
    patrolTasks,
    patrolRecords: MOCK_PATROL_RECORDS,
    workOrders,
    auditLogs,
  };
}

// 模拟报表列表
export const MOCK_REPORTS: ReportItem[] = [
  {
    id: 'RPT-20260904-01',
    reportCode: 'RPT-DAILY-20260904',
    title: '低碳园区微电网日度综合运营报表 (2026-09-04)',
    type: 'DAILY_OPERATION',
    period: '2026-09-04',
    generatedTime: '2026-09-05 01:15:00',
    author: '陈若涵 (运营主管)',
    status: 'COMPLETED',
    summary: '全站光伏发电 2,480 kWh，储能完成 1 次削峰填谷放电，充电桩消纳 920 kWh，关口购电 1,420 kWh，日净收益 1,984.00 元。设备可用率 99.6%，发生一般告警 1 起已闭环。',
    fileSize: '1.45 MB (CSV/PDF)',
    siteId: 'SITE-001',
    siteName: '低碳园区示范站',
    version: 'V1.0',
    tariffVersion: 'V1.0 (2026年工业峰谷电价)',
    tariffSchemeId: 'TARIFF-2026',
    revenueSnapshotId: 'REV-YEST-SETTLEMENT-V1',
    revenueSnapshotVersion: 'V1',
    revenueType: 'SETTLEMENT',
    isSettlementFormal: true,
    hasRiskWarning: false,
    dataConfidencePercent: 99.2,
    qualityLevel: 'NORMAL',
    traceId: 'TR-RPT-DAILY-20260904',
    payload: {
      pvGenerationKwh: 2480.0,
      pvSelfConsumptionKwh: 2291.5,
      chargingKwh: 920.0,
      gridPurchaseKwh: 1420.0,
      gridFeedInKwh: 188.5,
      storageChargeKwh: 650.0,
      storageDischargeKwh: 580.0,
      storageLossKwh: 70.0,
      pvRevenue: 3840.0,
      storageArbitrage: 1650.0,
      chargingRevenue: 2480.0,
      gridPurchaseCost: 4920.0,
      capacityBaseFee: 1066.0,
      netComprehensiveRevenue: 1984.0,
      totalAlarms: 1,
      criticalAlarms: 0,
      deviceAvailabilityRate: 99.6,
      detailsList: [
        { time: '00:00~06:00 (低谷)', item: '谷段储能充电受电', value: 650.0, unit: 'kWh', status: '正常', note: '储能充至 SOC 95%' },
        { time: '08:00~11:00 (高峰)', item: '光伏出力与高峰放电', value: 980.0, unit: 'kWh', status: '正常', note: '顶峰削峰，替代网电' },
        { time: '11:00~14:00 (平段/深谷)', item: '光伏大发与充电消纳', value: 1120.0, unit: 'kWh', status: '正常', note: '园区充电自用' },
        { time: '17:00~21:00 (高峰)', item: '晚高峰储能放电', value: 380.0, unit: 'kWh', status: '正常', note: 'SOC 放至 20%' },
      ],
    },
    versions: [
      {
        version: 'V1.0',
        generatedTime: '2026-09-05 01:15:00',
        author: '陈若涵 (运营主管)',
        tariffVersion: 'V1.0 (2026年工业峰谷电价)',
        revenueSnapshotVersion: 'V1',
        revenueSnapshotId: 'REV-YEST-SETTLEMENT-V1',
        dataConfidencePercent: 99.2,
        qualityFlag: 'NORMAL',
        changeReason: 'T+1 日终例行归档生成',
        fileSize: '1.45 MB',
        traceId: 'TR-RPT-DAILY-20260904',
      },
    ],
  },
  {
    id: 'RPT-20260904-REV-V1',
    reportCode: 'RPT-REV-20260904-V1',
    title: '示范站 T+1 收益结算报表 (2026-09-04 原始核算 V1.0)',
    type: 'REVENUE_SETTLEMENT',
    period: '2026-09-04',
    generatedTime: '2026-09-05 05:45:00',
    author: '收益结算引擎 (自动生成)',
    status: 'OUTDATED',
    summary: '【数据质量异常告警】因时代星云储能前置链路中断丢失 3 个采集窗口，削峰套利少计 286.50 元，置信度仅 71.4%（低于 95% 正式结算门禁），已阻断正式财务记账，标记为【待修正测算】。',
    fileSize: '1.18 MB (CSV/PDF)',
    siteId: 'SITE-001',
    siteName: '低碳园区示范站',
    version: 'V1.0',
    tariffVersion: 'V1.0 (2026年工业峰谷电价)',
    tariffSchemeId: 'TARIFF-2026',
    revenueSnapshotId: 'REV-YEST-SETTLEMENT-V1',
    revenueSnapshotVersion: 'V1',
    revenueType: 'ESTIMATE',
    isSettlementFormal: false,
    hasRiskWarning: true,
    riskDescription: '时代星云储能 EMS 发生连续通信中断，放电电量测点缺失，置信度 71.4% < 95.0% 门禁，收益不可正式记账。',
    dataConfidencePercent: 71.4,
    qualityLevel: 'ANOMALY',
    traceId: 'TR-REV-20260904-V1-RAW',
    outdatedReason: '已发起重算批次 TR-RECALC-20260905-0900，新版 V2.0 报表已生成，原报表归档对比保留。',
    payload: {
      pvRevenue: 3840.0,
      storageArbitrage: 1650.0, // 缺失时少计
      chargingRevenue: 2480.0,
      gridPurchaseCost: 4920.0,
      capacityBaseFee: 1066.0,
      netComprehensiveRevenue: 1984.0,
      dataConfidencePercent: 71.4,
      qualityIssueCount: 1,
      recalcBatchTraceId: '无 (原始异常核算)',
      detailsList: [
        { time: '2026-09-04', item: '屋顶光伏余电上网及自用收益', value: '+3,840.00', unit: '元', status: '正常', note: '自发自用率 92.4%' },
        { time: '2026-09-04', item: '电化学储能削峰填谷套利', value: '+1,650.00', unit: '元', status: '异常(少计)', note: '晚高峰通信断线导致 286.5 元未入账' },
        { time: '2026-09-04', item: '新能源汽车充电服务费与代收电费', value: '+2,480.00', unit: '元', status: '正常', note: '12 桩累计 920 kWh' },
        { time: '2026-09-04', item: '关口电网购电费用支出', value: '-4,920.00', unit: '元', status: '正常', note: '双向计量关口表' },
        { time: '2026-09-04', item: '变压器需量基本电费日分摊', value: '-1,066.00', unit: '元', status: '正常', note: '2,000 kVA 变压器申报需量' },
      ],
    },
    versions: [
      {
        version: 'V1.0',
        generatedTime: '2026-09-05 05:45:00',
        author: '收益结算引擎 (自动生成)',
        tariffVersion: 'V1.0',
        revenueSnapshotVersion: 'V1',
        revenueSnapshotId: 'REV-YEST-SETTLEMENT-V1',
        dataConfidencePercent: 71.4,
        qualityFlag: 'SUSPICIOUS_ANOMALY',
        changeReason: '初次核算（存在通信中断缺失，阻塞正式结算门禁）',
        fileSize: '1.18 MB',
        traceId: 'TR-REV-20260904-V1-RAW',
      },
    ],
  },
  {
    id: 'RPT-20260904-REV-V2',
    reportCode: 'RPT-REV-20260904-V2',
    title: '示范站 T+1 收益结算报表 (2026-09-04 修正重算版 V2.0)',
    type: 'REVENUE_SETTLEMENT',
    period: '2026-09-04',
    generatedTime: '2026-09-05 09:30:22',
    author: '陈若涵 (运营主管审核重算)',
    status: 'COMPLETED',
    summary: '【正式结算报表】基于补采插补的储能电量与 V1.0 官方批复电价重新核算，净收益差异额 +286.50 元（由 1,984.00 修正为 2,270.50 元）。数据置信度达到 99.5%，已通过正式结算门禁，归档保留 V1 与重算审计批次。',
    fileSize: '1.32 MB (CSV/PDF)',
    siteId: 'SITE-001',
    siteName: '低碳园区示范站',
    version: 'V2.0',
    tariffVersion: 'V1.0 (2026年工业峰谷电价)',
    tariffSchemeId: 'TARIFF-2026',
    revenueSnapshotId: 'REV-YEST-SETTLEMENT-V2',
    revenueSnapshotVersion: 'V2',
    revenueType: 'SETTLEMENT',
    isSettlementFormal: true,
    hasRiskWarning: false,
    dataConfidencePercent: 99.5,
    qualityLevel: 'PATCHED',
    traceId: 'TR-RECALC-20260905-0900',
    payload: {
      pvRevenue: 3840.0,
      storageArbitrage: 1936.5, // 修正后完整套利
      chargingRevenue: 2480.0,
      gridPurchaseCost: 4920.0,
      capacityBaseFee: 1066.0,
      netComprehensiveRevenue: 2270.5,
      dataConfidencePercent: 99.5,
      qualityIssueCount: 0,
      recalcBatchTraceId: 'TR-RECALC-20260905-0900',
      detailsList: [
        { time: '2026-09-04', item: '屋顶光伏余电上网及自用收益', value: '+3,840.00', unit: '元', status: '正常', note: '自发自用率 92.4%' },
        { time: '2026-09-04', item: '电化学储能削峰填谷套利 (补全)', value: '+1,936.50', unit: '元', status: '已修正重算', note: '补全断线 3 周期，核增收益 +286.50 元' },
        { time: '2026-09-04', item: '新能源汽车充电服务费与代收电费', value: '+2,480.00', unit: '元', status: '正常', note: '12 桩累计 920 kWh' },
        { time: '2026-09-04', item: '关口电网购电费用支出', value: '-4,920.00', unit: '元', status: '正常', note: '双向计量关口表' },
        { time: '2026-09-04', item: '变压器需量基本电费日分摊', value: '-1,066.00', unit: '元', status: '正常', note: '2,000 kVA 变压器申报需量' },
      ],
    },
    versions: [
      {
        version: 'V1.0',
        generatedTime: '2026-09-05 05:45:00',
        author: '收益结算引擎 (自动生成)',
        tariffVersion: 'V1.0',
        revenueSnapshotVersion: 'V1',
        revenueSnapshotId: 'REV-YEST-SETTLEMENT-V1',
        dataConfidencePercent: 71.4,
        qualityFlag: 'SUSPICIOUS_ANOMALY',
        changeReason: '初次核算（存在通信中断缺失）',
        fileSize: '1.18 MB',
        traceId: 'TR-REV-20260904-V1-RAW',
      },
      {
        version: 'V2.0',
        generatedTime: '2026-09-05 09:30:22',
        author: '陈若涵 (运营主管审核重算)',
        tariffVersion: 'V1.0',
        revenueSnapshotVersion: 'V2',
        revenueSnapshotId: 'REV-YEST-SETTLEMENT-V2',
        dataConfidencePercent: 99.5,
        qualityFlag: 'RECALCULATED_PASS',
        changeReason: '补采历史断线遥测后发起收益 V2 修正重算，达到正式财务归档门禁',
        fileSize: '1.32 MB',
        traceId: 'TR-RECALC-20260905-0900',
      },
    ],
  },
  {
    id: 'RPT-202608-M1',
    reportCode: 'RPT-MONTHLY-202608',
    title: '示范站 2026 年 8 月能效与综合收益月度报表',
    type: 'MONTHLY_SUMMARY',
    period: '2026-08',
    generatedTime: '2026-09-01 08:30:00',
    author: '陈若涵 (运营主管)',
    status: 'COMPLETED',
    summary: '全月微电网累计光伏发电 74,400 kWh，储能累计套利放电 17,400 kWh，充电桩群服务充电 27,600 kWh，月度综合净收益 59,520.00 元。月内清洗插补 2 次，平均数据置信度 99.4%。',
    fileSize: '2.85 MB (CSV/PDF)',
    siteId: 'SITE-001',
    siteName: '低碳园区示范站',
    version: 'V1.0',
    tariffVersion: 'V1.0 (2026年工业峰谷电价)',
    tariffSchemeId: 'TARIFF-2026',
    revenueType: 'SETTLEMENT',
    isSettlementFormal: true,
    hasRiskWarning: false,
    dataConfidencePercent: 99.4,
    qualityLevel: 'NORMAL',
    traceId: 'TR-RPT-MONTHLY-202608',
    payload: {
      pvGenerationKwh: 74400.0,
      pvSelfConsumptionKwh: 68745.0,
      chargingKwh: 27600.0,
      gridPurchaseKwh: 42600.0,
      gridFeedInKwh: 5655.0,
      storageChargeKwh: 19500.0,
      storageDischargeKwh: 17400.0,
      storageLossKwh: 2100.0,
      pvRevenue: 115200.0,
      storageArbitrage: 49500.0,
      chargingRevenue: 74400.0,
      gridPurchaseCost: 147600.0,
      capacityBaseFee: 31980.0,
      netComprehensiveRevenue: 59520.0,
      totalAlarms: 6,
      criticalAlarms: 0,
      deviceAvailabilityRate: 99.8,
      qualityIssueCount: 2,
      patchedPointsCount: 18,
      detailsList: [
        { time: '2026-08 第 1 周', item: '周度能效与收益', value: 13240.0, unit: '元', status: '正常', note: '光伏日均大发 2,450 kWh' },
        { time: '2026-08 第 2 周', item: '周度能效与收益', value: 14120.0, unit: '元', status: '正常', note: '夏季用电高峰，需量控制良好' },
        { time: '2026-08 第 3 周', item: '周度能效与收益', value: 16210.0, unit: '元', status: '正常', note: '储能深度峰谷套利' },
        { time: '2026-08 第 4 周', item: '周度能效与收益', value: 15950.0, unit: '元', status: '正常', note: '充电桩充电服务费稳步提升' },
      ],
    },
    versions: [
      {
        version: 'V1.0',
        generatedTime: '2026-09-01 08:30:00',
        author: '陈若涵 (运营主管)',
        tariffVersion: 'V1.0',
        dataConfidencePercent: 99.4,
        qualityFlag: 'NORMAL',
        changeReason: '月度运营财务月报归档',
        fileSize: '2.85 MB',
        traceId: 'TR-RPT-MONTHLY-202608',
      },
    ],
  },
  {
    id: 'RPT-202609-PATROL-01',
    reportCode: 'RPT-PATROL-202609-W1',
    title: '示范站现场运维巡检与隐患整改报表 (2026年9月第1周)',
    type: 'PATROL_MAINTENANCE',
    period: '2026-09-01 ~ 2026-09-05',
    generatedTime: '2026-09-05 18:00:00',
    author: '陈若涵 (运营主管复核归档)',
    status: 'COMPLETED',
    summary: '周期内例巡与测温周检任务 2 项，巡检完成率 100%，发现异常 1 起（特来电 4# 充电桩微动弹簧磨损卡滞），已派发现场消缺工单并完成润滑整改复核闭环。',
    fileSize: '1.65 MB (CSV/PDF)',
    siteId: 'SITE-001',
    siteName: '低碳园区示范站',
    version: 'V1.0',
    tariffVersion: 'N/A (非结算报表)',
    isSettlementFormal: false,
    hasRiskWarning: false,
    dataConfidencePercent: 100.0,
    qualityLevel: 'NORMAL',
    traceId: 'TR-RPT-PATROL-202609-W1',
    payload: {
      patrolPlansCount: 2,
      patrolTasksCount: 2,
      patrolCompletionRate: 100.0,
      patrolAbnormalCount: 1,
      workOrdersCount: 1,
      closedWorkOrdersCount: 1,
      totalAlarms: 1,
      deviceAvailabilityRate: 99.7,
      detailsList: [
        { time: '2026-09-04 17:10', item: '微电网核心设备日常例巡', value: '4项合格/1项保养', unit: '点检项', status: '已提交归档', note: '林志强点检，特来电4#桩微动润滑' },
        { time: '2026-09-05 06:00', item: '主回路电气接头红外热成像测温', value: '3项全部正常', unit: '测温回路', status: '已提交归档', note: '同相温差 ≤ 1.2℃，接触良好' },
        { time: '2026-09-04 18:30', item: '特来电4#桩微动弹簧润滑消缺工单', value: 'WO-20260904-001', unit: '闭环工单', status: '已复核关闭', note: '现场照片水印校验通过，陈若涵复核' },
      ],
    },
    versions: [
      {
        version: 'V1.0',
        generatedTime: '2026-09-05 18:00:00',
        author: '陈若涵 (运营主管)',
        tariffVersion: 'N/A',
        dataConfidencePercent: 100.0,
        qualityFlag: 'NORMAL',
        changeReason: '周度巡检消缺闭环归档',
        fileSize: '1.65 MB',
        traceId: 'TR-RPT-PATROL-202609-W1',
      },
    ],
  },
];


export const MOCK_PATROL_PLANS: PatrolPlan[] = [
  {
    id: 'PLAN-DAILY-01',
    planCode: 'PLAN-2026-D01',
    planName: '示范站微电网核心设备日常例巡规程',
    cycle: 'DAILY',
    route: '10kV 进线总降配电室 → 时代星云储能一体舱 → 1#、2#光伏逆变器区 → 特来电充电桩群',
    deviceScope: [
      '10kV 进线总降变双向关口电能表',
      '时代星云 500kW PCS',
      'CATL 磷酸铁锂户外电池舱',
      '1# 阳光电源 320kW 逆变器',
      '2# 阳光电源 320kW 逆变器',
      '特来电 120kW 快速充电桩群',
    ],
    templateItemsCount: 4,
    templateItems: [
      {
        id: 'CI-01',
        itemName: '时代星云 500kW PCS 变流柜主断路器状态检查',
        method: '目视与就地仪表核验',
        standard: '断路器闭合状态正常，就地指示灯常绿，无焦糊异味',
        deviceTarget: '时代星云 500kW PCS',
      },
      {
        id: 'CI-02',
        itemName: 'EMS 现场前置工控机 RS485/以太网通信接头',
        method: '线缆拔插紧固与指示灯核查',
        standard: 'RJ45 与端子排连接牢固，TX/RX 闪烁节拍与轮询一致',
        deviceTarget: '时代星云 500kW PCS',
      },
      {
        id: 'CI-03',
        itemName: 'CATL 储能电池集装箱空调与热管理管路温差',
        method: '红外测温枪实测',
        standard: '进回风温差在 3~5℃ 范围内，冷却水泵运行无异常震动',
        deviceTarget: 'CATL 磷酸铁锂户外电池舱',
      },
      {
        id: 'CI-04',
        itemName: '1#、2# 屋顶光伏组串逆变器交流并网箱防雷开关',
        method: '防雷器视窗检查',
        standard: '防雷视窗呈绿色，接地扁铁阻抗 < 4Ω',
        deviceTarget: '1# 阳光电源 320kW 逆变器',
      },
    ],
    status: 'ACTIVE',
    responsiblePerson: '林志强 (巡检员)',
    startDate: '2026-09-01',
    endDate: '2026-12-31',
    version: 'V1.0',
    description: '每日例巡全站光伏逆变、储能变流与电池舱热管理，确保通信正常、无过温发热。',
    lastGeneratedAt: '2026-09-05 06:00:00',
    nextRunTime: '2026-09-06 06:00:00',
    createdAt: '2026-09-01 09:00:00',
    updatedAt: '2026-09-01 09:00:00',
  },
  {
    id: 'PLAN-WEEKLY-02',
    planCode: 'PLAN-2026-W02',
    planName: '微电网主回路电气接头红外热成像测温周检',
    cycle: 'WEEKLY',
    route: '10kV 进线母排 → 直流汇流柜刀闸 → 储能升压变高低压套管',
    deviceScope: [
      '10kV 进线总降变双向关口电能表',
      '时代星云 500kW PCS',
      'CATL 磷酸铁锂户外电池舱',
    ],
    templateItemsCount: 3,
    templateItems: [
      {
        id: 'CI-W1',
        itemName: '变压器高低压侧铜排连接螺栓红外测温',
        method: 'Fluke 红外热像仪扫描',
        standard: '同相接触点温差 ≤ 3℃，绝对温升不超过环境 35K',
        deviceTarget: '10kV 进线总降变',
      },
      {
        id: 'CI-W2',
        itemName: '储能高压直流柜熔断器与快熔接触面热斑检测',
        method: '红外热像仪扫描',
        standard: '全视场无局部过热发红斑块，最高温度 < 65℃',
        deviceTarget: '时代星云 500kW PCS',
      },
      {
        id: 'CI-W3',
        itemName: '快充桩群强电进线开关电缆接线端子扭矩复核',
        method: '力矩扳手定扭抽检',
        standard: '紧固扭矩达标 45 N·m，无松动打火变色痕迹',
        deviceTarget: '特来电 120kW 快速充电桩群',
      },
    ],
    status: 'ACTIVE',
    responsiblePerson: '林志强 (巡检员)',
    startDate: '2026-09-01',
    endDate: '2026-12-31',
    version: 'V1.1',
    description: '每周一次对大电流刀闸与母排电缆压接头红外成像检测，防范电气接点发热松动隐患。',
    lastGeneratedAt: '2026-09-01 08:30:00',
    nextRunTime: '2026-09-08 08:30:00',
    createdAt: '2026-09-01 10:00:00',
    updatedAt: '2026-09-01 10:00:00',
  },
  {
    id: 'PLAN-MONTHLY-03',
    planCode: 'PLAN-2026-M01',
    planName: '全站消防、安全绝缘工器具与防雷接地网月度定检',
    cycle: 'MONTHLY',
    route: '全站安全用具室 → 储能气灭瓶组间 → 站区室外接地引下线',
    deviceScope: [
      '安全工器具与绝缘靴手套',
      '七氟丙烷气体灭火系统',
      '全站防雷接地网',
    ],
    templateItemsCount: 3,
    templateItems: [
      {
        id: 'CI-M1',
        itemName: '高压绝缘手套、验电器与接地线检测合格标签',
        method: '目视核验台账与试验标签',
        standard: '在有效检验周期内，无开裂老化漏气，试验周期未超期',
        deviceTarget: '安全用具室',
      },
      {
        id: 'CI-M2',
        itemName: '七氟丙烷储瓶称重与压力表指示核查',
        method: '目视压力表表盘',
        standard: '指针位于绿色正常工作压力区域 (2.5MPa 范围)',
        deviceTarget: '气灭瓶组间',
      },
      {
        id: 'CI-M3',
        itemName: '站区防雷引下线接地电阻摇测',
        method: '接地电阻测试仪',
        standard: '工频接地电阻 ≤ 4.0 Ω，焊接搭接无锈蚀',
        deviceTarget: '室外接地引下线',
      },
    ],
    status: 'PAUSED',
    responsiblePerson: '陈若涵 (运营人员)',
    startDate: '2026-08-01',
    endDate: '2026-12-31',
    version: 'V1.0',
    description: '每月核验绝缘手套/绝缘杆试验标签、气灭压力表指针、接地扁铁防腐蚀情况。',
    lastGeneratedAt: '2026-08-05 09:00:00',
    nextRunTime: '2026-09-10 09:00:00',
    createdAt: '2026-08-01 14:00:00',
    updatedAt: '2026-08-01 14:00:00',
  },
];

export const MOCK_PATROL_RECORDS: PatrolRecord[] = [
  {
    id: 'REC-20260904-001',
    recordCode: 'REC-20260904-001',
    taskId: 'TASK-HIST-01',
    taskCode: 'PATROL-20260904-D1',
    taskTitle: '示范站微电网核心设备日常例巡 (2026-09-04)',
    taskSource: 'PLAN',
    planId: 'PLAN-DAILY-01',
    planName: '示范站微电网核心设备日常例巡规程',
    planVersionSnapshot: 'V1.0 (2026-09-01 发布规程快照)',
    submitter: '林志强 (巡检员)',
    submittedTime: '2026-09-04 17:10:25',
    archivedTime: '2026-09-04 17:35:10',
    archivedBy: '陈若涵 (运营人员)',
    syncStatus: 'SYNCED',
    devices: [
      '时代星云 500kW PCS',
      'CATL 磷酸铁锂户外电池舱',
      '1# 阳光电源 320kW 逆变器',
      '特来电 4# 直流充电桩',
    ],
    items: [
      {
        id: 'RCI-01',
        deviceName: '时代星云 500kW PCS',
        itemTitle: 'PCS 变流柜主断路器状态检查',
        standard: '断路器闭合状态正常，就地指示灯常绿，无焦糊异味',
        result: 'NORMAL',
        remark: '指示灯常绿，仪表电压 400V 平衡，运行无异响',
        hasPhotoPlaceholder: false,
      },
      {
        id: 'RCI-02',
        deviceName: '时代星云 500kW PCS',
        itemTitle: 'EMS 现场前置工控机通信接头',
        standard: 'RJ45 与端子排连接牢固，TX/RX 闪烁节拍与轮询一致',
        result: 'NORMAL',
        remark: 'TX/RX 闪烁正常，Modbus 报文轮询无丢帧',
        hasPhotoPlaceholder: false,
      },
      {
        id: 'RCI-03',
        deviceName: 'CATL 磷酸铁锂户外电池舱',
        itemTitle: '空调与热管理管路温差',
        standard: '进回风温差在 3~5℃ 范围内，冷却水泵运行无异常震动',
        result: 'NORMAL',
        remark: '实测进风 22.4℃，回风 26.1℃，温差 3.7℃ 符合规范',
        hasPhotoPlaceholder: false,
      },
      {
        id: 'RCI-04',
        deviceName: '特来电 4# 直流充电桩',
        itemTitle: '充电连接器插拔卡扣微动弹簧磨损',
        standard: '锁紧到位电阻正常，插拔顺畅无卡滞',
        result: 'ABNORMAL',
        remark: '现场日常插拔次数累计达到保养阈值，微动有卡滞，已现场清洁并润滑校正。',
        hasPhotoPlaceholder: true,
        photoMeta: {
          timestamp: '2026-09-04 16:45:12',
          coordinate: '117.65°E, 24.52°N',
          locationName: '示范站特来电充电区 4# 桩就地',
        },
      },
    ],
    abnormalCount: 1,
    abnormalSummary: '特来电 4# 桩插拔微动卡扣偶发微滞，已现场润滑复测合格，闭环归档。',
    linkedAlarmCode: 'ALM-CHG-004',
    linkedWorkOrderCode: 'WO-20260904-001',
    traceId: 'TR-20260904-CHG-MAINT',
    inspectorRemark: '全站一次与二次设备工作正常，特来电 4# 桩微动已保养复测，建议下周重点观察。',
    status: 'ARCHIVED',
  },
];

export const MOCK_PATROL_PLAN = MOCK_PATROL_PLANS[0];
